data/ui/widgets/status.ui, src/Widgets/Status.vala
I added this feature to show the count of replays. If one is replayed, 1 is shown and if more than 1, +1 is shown.
=> Add reply count

data/dev.geopjr.tooth.desktop.in
As GTK apps do this just fine let's have a splash
under phosh.
=> desktop: Indicate we can handle StartupNotify

data/gresource.xml, data/ui/widgets/status.ui, data/ui/widgets/votebox.ui, flake.lock, meson.build, po/dev.geopjr.tooth.pot, src/API/Entity.vala, src/API/Poll.vala, src/API/PollOption.vala, src/API/Status.vala, src/Utils/DateTime.vala, src/Widgets/Status.vala, src/Widgets/VoteBox.vala, src/Widgets/VoteCheckButton.vala
This code allows to poll in Tooth. You can view, and vote but not create a poll. 
Viewing:
Voting:
=> poll support

data/ui/dialogs/preferences.ui, src/Application.vala
Currently background mode works by hiding the window. Also in this mode we need to send notification when a new toot is sent
=> Background Mode

po/LINGUAS, po/POTFILES, po/de_DE.po, po/dev.geopjr.tooth.pot, po/es.po, po/fr.po, po/pt_BR.po, po/ru_RU.po
This is based on #34, so please check that first.
=> Add Brazilian Portuguese translation

data/dev.geopjr.tooth.gschema.xml, data/ui/dialogs/preferences.ui, src/Application.vala, src/Dialogs/Preferences.vala, src/Services/Settings.vala
Fixes #17 
In this merge request, I implement a Color Scheme switcher that allows changing from this system, light and dark. I will do a little self review too.
[Grabación de pantalla desde 2022-12-22 00-19-08.webm](https://user-images.githubusercontent.com/76420970/209070864-730dc79a-4baf-4a80-bcd6-7174bf09dd34.webm)
=> Add a Color Scheme Preference

src/Widgets/Status.vala
This PR partially f!xes #53. It's based on the `BindingGroup` patch proposed there, but without breaking spoilers.
=> Fix leaking Status widgets

.github/workflows/build.yml
Related to https://github.com/GeopJr/Tooth/issues/41.
=> workflow: Build for aarch64

data/ui/views/base.ui, src/Views/Base.vala, src/Views/Timeline.vala
=> new design for StatusPage

src/Application.vala
[GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html)
=> Add `Ctrl+Q` quit shortcut

data/style.css, data/ui/widgets/status.ui, src/Widgets/EmojiLabel.vala, src/Widgets/RichLabelContainer.vala, src/Widgets/Status.vala
=> feat: status heading redesign

data/ui/widgets/status.ui, src/Widgets/Status.vala
=> fix(Status): actions spread

data/ui/views/profile_header.ui, src/Views/Profile.vala
=> feat(Profile): move follow button to the cover

src/Widgets/Status.vala, src/Widgets/StatusActionButton.vala
fix: #101 
There's still a problem with bindings - formal_bindings are not getting updated
=> feat(Status): show action counts

src/Services/Accounts/SecretAccountStore.vala
=> fix(SecretAccountStore): unlock items while searching

src/Services/Accounts/SecretAccountStore.vala
=> fix(SecretAccountStore): schema do not match name

.github/workflows/build.yml, build-aux/snap/snapcraft.yaml
Try this now, I have added the access to home folder. Added network access, and removed unnecessary deps. Check now if things are fine now.
=> Fixed and reduced the snap size

src/API/Instance.vala, src/Services/Accounts/InstanceAccount.vala
=> fix(notifications): mark as read for Pleroma

data/ui/views/profile_header.ui, src/Dialogs/MainWindow.vala, src/Views/MediaViewer.vala, src/Views/Profile.vala, src/Widgets/Background.vala
fix: #194 
Unsure whether expanding on media viewer's add_image/video functions would be better - this approach seems cleaner however
=> feat(profile): show avatar header

src/API/Conversation.vala, src/Application.vala, src/Dialogs/Composer/AttachmentsPage.vala, src/Widgets/Attachment/Box.vala, src/Widgets/Status.vala
Found via `typos --format brief`
=> docs: fix typos

src/Services/Accounts/SecretAccountStore.vala, src/Services/Cache/ImageCache.vala, src/Widgets/Status.vala, src/Widgets/StatusActionButton.vala
This doesn't fix __ #182 #231 - those will probably be fixed by #179
This PR:
- converts some sync operations to async
- especially the pixbuf one - making loading images significantly less laggy (at least from my limited tests)
- and finally drops the bindings for the status widgets for the reasons mentioned on #179 (needs more testing)
=> fix some performance issues

src/Views/Timeline.vala
This is a weird one.
Timeline wouldn't get destroyed and after lot's of debugging, this worked :shrug:
=> fix(Timeline): memory leak

src/Application.vala, src/Services/Accounts/SecretAccountStore.vala
wiki page: https://github.com/GeopJr/Tuba/wiki/keyring-issues
cc: @chri2
fix: #117
=> feat(SecretAccountService): helpful message on libsecret issues

data/style-dark.css, data/style.css, src/Widgets/Conversation.vala, src/Widgets/Status.vala
=> feat: visually indicate direct posts

src/Dialogs/Composer/Dialog.vala, src/Views/Thread.vala, src/Widgets/MarkupView.vala, src/Widgets/Status.vala
=> feat:reactive post updates

src/API/Tag.vala, src/Services/Network/Request.vala, src/Views/Hashtag.vala, src/Widgets/RichLabel.vala
=> fix: treat path as encoded

src/API/Entity.vala, src/API/Funkwhale.vala, src/API/Funkwhale/Track.vala, src/API/Funkwhale/meson.build, src/API/Status/PreviewCard.vala, src/API/meson.build, src/Dialogs/MainWindow.vala, src/Views/MediaViewer.vala, src/Widgets/Status.vala
Since PeerTube was added, why not add Funkwhale too! :whale:
This PR also adds user friendly URLs for the remote media
=> feat(PreviewCard): Funkwhale support

data/style.css, src/API/BookWyrm.vala, src/API/BookWyrm/Author.vala, src/API/BookWyrm/Cover.vala, src/API/BookWyrm/meson.build, src/API/Entity.vala, src/API/Status/PreviewCard.vala, src/API/meson.build, src/Dialogs/MainWindow.vala, src/Widgets/BookWyrmPage.vala, src/Widgets/Status.vala, src/Widgets/meson.build
=> feat(PreviewCard): BookWyrm support

src/Widgets/Attachment/Box.vala
Taken from #181 
> **Warning**
This does not fix _ #180, it needs finer height / width control. This is partially implemented so it makes it in the next release.
=> feat(Widgets.Attachment.Box): make single attachment bigger

src/Widgets/VoteCheckButton.vala
=> fix: change vote check button alignment to center

data/ui/views/sidebar/view.ui
=> feat(sidebar): smaller width

src/Dialogs/MainWindow.vala, src/Views/Base.vala, src/Views/Profile.vala, src/Views/Thread.vala
=> fix(Thread): allow nesting

src/Views/Profile.vala
=> fix(profile): reload pinned posts on refresh

src/Views/Base.vala, src/Views/ContentBase.vala, src/Views/Timeline.vala
=> feat(Timeline): pull to refresh

src/Widgets/PreviewCard.vala
=> feat(PreviewCard): design changes

data/ui/dialogs/compose.ui, src/Dialogs/Composer/AttachmentsPage.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/EditorPage.vala, src/Dialogs/Composer/Page.vala, src/Dialogs/Composer/PollPage.vala, src/Services/Network/Request.vala, src/Widgets/Attachment/Box.vala, src/Widgets/Status.vala
fix: #316 ?
fix: #263 ? (I just noticed this issue)
fix: #319 
~~todo:~~
- ~~finish alt text editing~~
- ~~add alt text changed on equal ()~~
=> feat(Composer): show dialog on exit

src/Dialogs/NewAccount.vala, src/Services/Network/Request.vala
pixelfed requires /oauth/token to be form data
fix: #318 
The pagination issue is still a blocker :shrug: but it should now be somewhat usable
=> feat: Pixelfed

data/ui/widgets/status.ui
=> feat(status): hiding revealed spoilers

src/Views/Thread.vala
=> fix(Thread): segfault

Makefile, meson.build, src/Utils/Html.vala, src/Widgets/RichLabel.vala, tests/DateTime.test.vala, tests/Html.test.vala, tests/Tracking.test.vala, tests/meson.build
fix: #306 
I'm not super fond of the way unit testing works but it will do for now :shrug:
=> feat: tests

data/style.css, src/API/Status.vala, src/Widgets/Attachment/Box.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/Status.vala
=> feat(attachments): spoilers

src/Dialogs/NewAccount.vala
This should fix auto-login on *oma
=> fix(NewAccount): parse url params instead

src/Dialogs/Composer/Completion/CompletionProvider.vala
=> feat(Composer): check if word has trigger when not triggering

src/Services/Accounts/SecretAccountStore.vala
fix: #358 
libsecret issues should point users to Tuba's libsecret wiki page org.freedesktop.DBus.Error.ServiceUnknown
=> feat(SecretAccountService): point libsecret errors to the libsecret wiki page

src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/Page.vala
fix: #65 #284
This breaks HIG but it's needed as it conflicts with usability
=> feat(Composer): move actionbar to the top on narrow

data/style.css, src/API/Account/Source.vala, src/API/Instance.vala, src/API/Pleroma/Instance.vala, src/API/Pleroma/Status.vala, src/API/Pleroma/meson.build, src/API/Status.vala, src/API/meson.build, src/Dialogs/ProfileEdit.vala, src/Dialogs/meson.build, src/Services/Accounts/InstanceAccount.vala, src/Services/Accounts/SecretAccountStore.vala, src/Services/Network/Network.vala, src/Services/Network/Request.vala, src/Views/Profile.vala
fix: #364 
TODO:
- ~~test on *oma~~
- ~~test > 4 fields on glitch~~
- ~~check if new saving format breaks already saved keys~~
- ~~test errors (large files etc)~~
- ~~save on update_credentials cb~~
- ~~remove self from entity cache?~~
=> feat(Profile): editing

data/style.css, src/Views/MediaViewer.vala
=> feat(MediaViewer): do not use osd

data/ui/widgets/status.ui
- warning iconn valign center
- hexpand label instead of aligning to start
=> feat(status): minor revealed spoiler UI changes

data/ui/views/sidebar/item.ui
fix: #401
fix: https://github.com/GeopJr/Tuba/issues/273#issuecomment-1642383460
=> fix(sidebar): ellipsize places

src/Widgets/CustomEmojiChooser.vala
=> feat(CustomEmojiChooser): sort emojis & categories alphabetically

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Views/Timeline.vala, src/Widgets/EmojiLabel.vala, src/Widgets/MarkupView.vala, src/Widgets/RichLabel.vala
=> feat: large emoji size

src/Dialogs/Composer/AttachmentsPage.vala
partial: https://github.com/GeopJr/Tuba/issues/411#issuecomment-1648241010
=> feat(Composer)[Media]: dnd

data/style.css
[Screencast from 2023-08-05 00-47-54.webm](https://github.com/GeopJr/Tuba/assets/18014039/8897aa19-bd46-453e-bdcd-d195dc33c6d7)
=> feat(style): status buttons animations

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Accounts/InstanceAccount.vala, src/Services/Settings.vala
=> feat(Settings): mute notification types

build-aux/dev.geopjr.Tuba.Devel.json, meson.build, src/Widgets/VoteBox.vala
=> fix: Vala 0.56.11 vapi change  & GTK 4.12 deprecation

data/ui/views/sidebar/view.ui, src/Application.vala, src/Views/Sidebar.vala
and move the misc from the sidebar there
=> feat(Sidebar): replace compose button with a menu button

data/style.css, data/ui/views/base.ui, src/Views/Base.vala, src/Views/ContentBase.vala, src/Views/Home.vala
=> feat(Home): prominent compose button

data/gtk/help-overlay.ui
- Fix overflowing the Go Back entry
- Add missing shortcuts: Close Window, About, Scroll Up, Scroll Down
=> data: Update Help Overlay

src/Widgets/MarkupView.vala
=> feat(MarkupView): handle ordered lists

data/style.css, src/Widgets/Attachment/Box.vala
=> feat(Attachment.Box): sensitive overlay redesign

data/ui/widgets/status.ui, src/Widgets/Status.vala
fix: #471 
GTK regression? https://gitlab.gnome.org/GNOME/gtk/-/issues/3651
needs to be investigated
=> fix(Status): avis overflowing

src/Widgets/Status.vala
=> fix(Status): remove reactions row if it exists

data/style.css, src/Widgets/MarkupView.vala
=> feat(MarkupView): blockquote fixes

src/Views/Timeline.vala
similar to the media viewer background
The way sizing works had to change to use width_request instead of depending on halign being fill
=> feat(Timeline): pull to refresh spinner background

src/Services/Cache/ImageCache.vala
=> fix(ImageCache): attempt to fix orientation

data/ui/menus.ui, src/Views/Sidebar.vala
=> feat: refresh action on sidebar menu

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Widgets/Attachment/Image.vala, src/Widgets/PreviewCard.vala
Allow disabling blurhash generation
=> feat(settings): blurhash

data/style.css, data/ui/dialogs/main.ui, data/ui/views/sidebar/account.ui, data/ui/views/sidebar/view.ui, src/Views/Sidebar.vala
=> feat(sidebar): account switcher popover

data/style.css
=> feat(Timeline): add borders on small content

src/Dialogs/Composer/AttachmentsPage.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Views/MediaViewer.vala, src/Widgets/Attachment/Item.vala
=> feat(Media): remove arrows and point at pointer

src/Widgets/Status/ActionsRow.vala
=> fix(ActionsRow): bidirectional active state

src/Views/Search.vala
if your search starts with `#` then it's safe to assume you are looking for a hashtag and the "All" tab should show them first
=> feat(Search): order based on type

po/POTFILES, po/dev.geopjr.Tuba.pot
1 more string, hopefully doesn't mess up the weblate pr
=> chore(po): bump

data/ui/views/sidebar/account.ui, po/POTFILES, po/dev.geopjr.Tuba.pot, src/Views/Sidebar.vala
=> fix(AccountSwitcher): translations, tooltips, dialog wrap

src/Application.vala
=> fix: only execute app.compose when there is instance info

src/Dialogs/Composer/EditorPage.vala
=> feat(composer): remove view styling from sourceview

src/Views/Sidebar.vala
=> fix(sidebar): about => about tuba

data/ui/menus.ui, src/Views/Profile.vala
=> feat(profile): open in browser action

data/dev.geopjr.Tuba.desktop.in, src/Application.vala, src/Dialogs/NewAccount.vala, src/Utils/WebApHandler.vala, src/Utils/meson.build, tests/WebApHandler.test.vala, tests/meson.build
fix: #559
Handle web+ap links per https://fedilinks.org/spec/en/6-The-web-ap-URI
=> feat: web+ap support

data/ui/menus.ui, src/API/Relationship.vala, src/Views/Profile.vala
=> feat(Profile): notify on new user post

data/style.css, src/Views/Home.vala
fix: #548
- margin can only be animated if handled by CSS
- some notify signals around is-mobile, for when main_window is ready and when it changes to false to show the button on wide mode
=> feat(home): composer button improvements

src/API/Status.vala
=> fix(API.Status): invalid property name

data/ui/widgets/status.ui, src/Widgets/LabelWithWidgets.vala, src/Widgets/MarkupView.vala, src/Widgets/ProfileCover.vala, src/Widgets/RichLabel.vala
=> feat(RichLabel): do not use-markup by default

src/Views/MediaViewer.vala
Sometimes you have to wonder what exactly is the meaning of `?.`. I assumed it acted similarly to ecmascript's optional chaining but it clearly doesn't.
Two fixes:
- if pos < -1
- expand `?.`
fix: #577
=> fix(MediaViewer): index out of bounds

src/Dialogs/Composer/EditorPage.vala
=> fix(Composer): allow caps lock on ctrl + enter

data/dev.geopjr.Tuba.gschema.xml, src/Dialogs/Saveable.vala
Remembers whether or not the window was maximized when last closed.
=> Enhancement: Apply window maximized state from previous session to new session

src/Views/Timeline.vala
=> feat(Timeline): do not use base status for pagination errors

src/Widgets/MarkupView.vala
fix: https://github.com/GeopJr/Tuba/issues/574#issuecomment-1752108404
=> fix(MarkupView): let blockquote handler handle pre->code

src/Views/Timeline.vala
=> feat(Timeline): only accept new posts if the initial refresh has finished

data/ui/views/base.ui, data/ui/views/media_viewer.ui, src/Views/Home.vala
=> fix: floating button focus style getting cut off

src/Services/Accounts/Mastodon/Account.vala, src/Views/Base.vala, src/Views/Main.vala
including the fake ones
fix: #604
=> feat: remove back arrow from sidebar items

data/ui/views/base.ui, src/Views/Main.vala
fix: #517
TODO: remove the whole notify signal when #648 gets merged
=> feat(base): do not toggle between toolbarview styles

data/ui/views/media_viewer.ui
=> fix(mediaviewer): headerbar items order

src/Views/Main.vala, src/Views/TabbedBase.vala
Instead of having 2 breakpoints for the title stack, use the tabbedbase one only :shrug: 
fix: mentioned in circle
=> fix(Views)[main]: breakpoint race condition

data/ui/views/media_viewer.ui, src/Views/MediaViewer.vala
=> feat(mediaviewer): remove carousel dots

src/Widgets/ProfileCover.vala
=> feat(ProfileCover): show unshortened unit in tooltip

data/gtk/help-overlay.ui, data/ui/views/media_viewer.ui, src/Views/MediaViewer.vala
=> feat(mediaviewer): shortcut improvements

src/Views/Sidebar.vala
feat(AccountSwitcher): open new dialog on plus icon click
fix(AccountSwitcher): close popup on icon click
fix: #654
=> feat(AccountSwitcher): show plus icon instead of user

src/Utils/WebApHandler.vala, tests/WebApHandler.test.vala
Unused and shouldn't be passed to resolve
=> feat(WebApHandler): drop userinfo

data/style.css, src/Dialogs/Composer/Completion/EmojiProvider.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala
Ours looked a bit outdated, it should now somewhat resemble Fractal's
| | Handle | Tag | Emoji |
| --- | :---: | :---: | :---: |
| Before | ![Screenshot from 2023-11-26 02-12-05](https://github.com/GeopJr/Tuba/assets/18014039/d6f1635c-f061-4e23-ad1c-3bdd5c6e8989) | ![Screenshot from 2023-11-26 02-12-13](https://github.com/GeopJr/Tuba/assets/18014039/b6d78427-390c-4ec8-a254-a6692c7e12f9) | ![Screenshot from 2023-11-26 02-12-19](https://github.com/GeopJr/Tuba/assets/18014039/6557c41c-bfe0-40fa-86d3-3f5a845e1217) |
| After | ![Screenshot from 2023-11-26 02-12-56](https://github.com/GeopJr/Tuba/assets/18014039/e57b0cae-21f4-4582-b7ff-eba06dea401b) | ![Screenshot from 2023-11-26 02-13-16](https://github.com/GeopJr/Tuba/assets/18014039/3a850e2c-470a-4de3-a5dc-6c97e7d20843) | ![Screenshot from …
=> feat(CompletionProvider): match Fractal's design

src/Dialogs/Composer/Completion/CompletionProvider.vala, src/Dialogs/Composer/Completion/EmojiProvider.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala
fix: #660 
among other things it also fixed the word replacement strategy by replacing the whole word instead of appending
=> fix(CompletionProvider): refactor word capturing logic

src/Views/MediaViewer.vala
=> feat(MediaViewer): loop and autoplay gifs

src/Services/Accounts/Mastodon/Account.vala
fix: https://github.com/GeopJr/Tuba/issues/604#issuecomment-1840692801
=> fix(sidebar): treat sidebar search as a sidebar item

po/dev.geopjr.Tuba.pot, src/Utils/DateTime.vala
! count == 0 => plural
fix: #690
=> chore(DateTime): use plurals

src/API/Instance.vala, src/API/Pleroma/Instance.vala, src/API/Status.vala, src/Dialogs/Composer/Dialog.vala, src/Widgets/Status/ActionsRow.vala
Advanced Reblog/Boost Dialog actual quote support when available
TODO:
- ~~actually test it~~
=> feat(ARD): actually quote when supported

src/Widgets/ProfileCover.vala
=> fix(ProfileCover): add separators

src/Widgets/MarkupView.vala
=> fix(MarkupView): handle weirder structures

src/Dialogs/MainWindow.vala, src/Services/Accounts/Mastodon/Account.vala
fix: #710
TODO:
- ~~check other combinations~~
=> fix: set sidebar item when one of the fake pages is selected

src/Utils/DateTime.vala, tests/DateTime.test.vala
Yikes how did I miss this
\+ fix tests
=> fix(DateTime): is_3_months_old being year aware

src/Views/Base.vala
fix: https://github.com/GeopJr/Tuba/pull/648#issuecomment-1868146320
fix: #722
=> fix(Base): narrow mode should always have a back arrow

data/ui/views/media_viewer.ui, src/Views/MediaViewer.vala
RTL back button should point right
=> fix(MediaViewer): back button icon on RTL

src/Dialogs/MainWindow.vala
per Alice's advice (https://gitlab.gnome.org/GNOME/libadwaita/-/issues/775#note_1963218), we should replace all navigationview pages even from Home
=> fix(MainWindow): replace navigationview pages on all sidebar items

src/Widgets/LabelWithWidgets.vala, src/Widgets/MarkupView.vala, src/Widgets/RichLabel.vala
fix: #756
partially revert: #644 
More details on #756, this is a temp hack.
=> fix(LWW): temp hack to fix status overflow

data/ui/views/sidebar/account.ui, src/Views/Sidebar.vala
=> feat(account_switcher): notification badges

data/dev.geopjr.Tuba.1.in, data/meson.build
=> feat(data): manpage

src/Utils/Tracking.vala
I saw these tracking IDs in the willd.
=> Tracking: add more tracking IDs

data/style.css, src/Services/Accounts/Mastodon/Account.vala, src/Services/Accounts/Places.vala, src/Views/Home.vala, src/Views/Sidebar.vala, src/Views/Timeline.vala
If you've scrolled down, new posts will be badged
=> feat(home): new posts badge

src/Views/MediaViewer.vala, src/Widgets/Attachment/Item.vala
=> feat: cleanup attachment downloading

data/ui/views/media_viewer.ui, src/Widgets/Attachment/Item.vala
=> fix: ellipsize 'Save Media' strings

src/Dialogs/Composer/AttachmentsPage.vala
=> fix(composer): keep media sensitivity on edit

src/Widgets/Notification.vala, src/Widgets/Status.vala
=> feat(notifications): remove preview cards from own posts

src/Application.vala, src/Dialogs/Composer/EditorPage.vala, src/Utils/Counting.vala, src/Utils/meson.build, tests/Counting.test.vala, tests/meson.build
At last! Composer counter feature parity
| Tuba | Mastodon |
| :---: | :---: |
| ![Screenshot from 2024-03-03 00-49-22](https://github.com/GeopJr/Tuba/assets/18014039/5655e1b3-919f-4286-92cd-ae5749f6fbf5) | ![Screenshot from 2024-03-03 00-49-45](https://github.com/GeopJr/Tuba/assets/18014039/c82bf190-e512-47db-b722-adaba0e8b548) |
Also moved all counters to utils so we test them and re-use them.
fix: #484
=> feat(composer): correctly count mentions

data/dev.geopjr.Tuba.gschema.xml, src/Services/Settings.vala, src/Widgets/CustomEmojiChooser.vala
=> feat(cec): recent emojis

meson.build, src/Application.vala, src/Build.vala.in
- Support website => matrix
- Issues => github
- Introduced wiki, translations, donate
=> feat(about): more links

data/ui/views/base.ui, src/Views/Announcements.vala, src/Views/Base.vala, src/Views/Bookmarks.vala, src/Views/ContentBase.vala, src/Views/Conversations.vala, src/Views/EditHistory.vala, src/Views/Explore.vala, src/Views/Favorites.vala, src/Views/Federated.vala, src/Views/FollowRequests.vala, src/Views/Hashtags.vala, src/Views/Lists.vala, src/Views/Local.vala, src/Views/Notifications.vala, src/Views/Profile.vala, src/Views/Search.vala, src/Views/StatusStats.vala, src/Views/TabbedBase.vala, src/Views/Timeline.vala
Mainly Circle points:
- Custom empty state title instead of "Nothing to see here" per view
- Removed symbolic from status
=> feat(base_status): redesign

src/Views/Sidebar.vala
https://github.com/GeopJr/Tuba/issues/612#issuecomment-1955879631
=> feat(headerbar): add new post in menu

src/Application.vala, src/Dialogs/MainWindow.vala
=> feat: disable gtk-label-select-on-focus

src/Dialogs/DevConsole.vala, src/Views/Home.vala
- Home 'new posts'
- Unread announcements
- Unreviewed follow requests
=> feat(devmode): more counters

data/ui/views/sidebar/view.ui
Accidentally broke it when adding the follow requests one - it should be its own child
=> fix(sidebar): announcements banner

data/ui/dialogs/compose.ui
Fix https://github.com/GeopJr/Tuba/issues/849
=> fix(Composer): Show confirmation dialog on exit

data/dev.geopjr.Tuba.metainfo.xml.in
=> feat(metainfo): brand colors & developer id

data/ui/dialogs/new_account.ui, data/ui/dialogs/profile_edit.ui, data/ui/views/base.ui, data/ui/views/sidebar/view.ui, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/MainWindow.vala, src/Dialogs/Report.vala, src/Views/Profile.vala, src/Widgets/Attachment/Item.vala
=> feat: set centering policy to strict on all headerbars

data/ui/dialogs/compose.ui, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Report.vala
=> feat(Dialogs): use close-attempt instead of actions

data/dev.geopjr.Tuba.metainfo.xml.in
fix: #863 
🐬˚˖𓍢ִ໋ 🐋✧˚.🐟⋆🎐🫧🦋🧿💠🌀
=> feat(metainfo): new branding colors

.github/workflows/msys2.yml
=> feat(ci): re-enable windows

src/Services/Accounts/InstanceAccount.vala, src/Views/Thread.vala, src/Widgets/Status.vala
=> feat(status): reply kind indicator if there's no other

data/style.css, src/Widgets/ProfileCover.vala
Instead of horizontal alignment, make them vertical
Also use LWW for the titles as they accept custom emojis
fix: #905
=> feat(profile-cover): redesign fields

data/dev.geopjr.Tuba.gschema.xml, src/Services/Settings.vala, src/Views/MediaViewer.vala
=> feat(MV): remember last volume set

data/langs/fedi-basic.lang
=> fix(syntax-highlighting): hashtag parsing being too liberal

data/style.css, src/Widgets/ProfileCover.vala
fix: #905
TODO:
- edge cases
- leak test
=> feat(profile-cover): fields design

src/Widgets/MarkupView.vala, src/Widgets/Status.vala
=> fix(status): don't remove 'quote-inline' elements if there's no quote

src/API/Relationship.vala, src/Widgets/RelationshipButton.vala
Don't know how we missed this lol
fix: #916
=> fix(relationship): blocked_by

data/style.css, data/ui/views/profile_header.ui, src/API/Relationship.vala, src/Widgets/ProfileCover.vala
=> feat(Profile): notes

src/Dialogs/Composer/PollPage.vala
=> feat(composer): set default poll exp time to 1D if available

data/ui/dialogs/main.ui
600 was too much for the OSK to fit
294 looks like the best size before stuff starts breaking
=> feat(MainWindow): lower height request

data/style-dark.css, data/style.css, data/ui/views/base.ui, data/ui/views/profile_header.ui, data/ui/views/sidebar/account.ui, data/ui/widgets/announcement.ui, data/ui/widgets/profile.ui, data/ui/widgets/status.ui, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Utils/DateTime.vala, src/Views/Base.vala, src/Views/ContentBase.vala, src/Views/Profile.vala, src/Views/Search.vala, src/Widgets/Account.vala, src/Widgets/Announcement.vala, src/Widgets/Attachment/Item.vala, src/Widgets/CustomEmojiChooser.vala, src/Widgets/Emoji.vala, src/Widgets/EmojiLabel.vala, src/Widgets/LabelWithWidgets.vala, src/Widgets/MarkupView.vala, src/Widgets/ProfileCover.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala, src/Widgets/Status/ActionsRow.vala, src/Widgets/Status/ReactionsRow.vala, src/Widgets/StatusActionButton.vala, src/Widgets/VoteBox.vala
A big and important one.
Accessibility is kind-of not up to standard. We can do better.
- LabelWithWidgets uses a label and places the custom widgets (emojis) on top. It uses a placeholder in the positions those widgets are. When a screen reader reads the label, it doesn't read the custom emojis' labels (names) in place of the placeholder. To fix that, we replace the label's aria label with the current text while replacing the placeholders with the widgets' tooltip text
- Profile covers did not announce the relationship label
- Profile covers and avatars are announced as buttons. That wasn't informative. They now have a tooltip text about the action they perform when clicked
- Posts announced the date but it was bad, '1m' is not informative. They now announce and show a tooltip text of …
=> feat: improve accessibility

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/new_account.ui, data/ui/dialogs/preferences.ui, src/Application.vala, src/Dialogs/NewAccount.vala, src/Dialogs/Preferences.vala, src/Services/Accounts/InstanceAccount.vala, src/Services/Helpers/Image.vala, src/Services/Network/Network.vala, src/Services/Settings.vala, src/Views/Sidebar.vala
fix: #788 
fix: #135 
Should gracefully recover
=> feat: in-app proxy settings

src/Widgets/ProfileCover.vala
=> feat(ProfileCover): show stats on mini and aria

src/Views/Base.vala, src/Views/StatusStats.vala, src/Views/TabbedBase.vala
https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues/112
=> feat: use different empty state icon in some timelines

data/gresource.xml, data/ui/dialogs/advanced_search.ui, data/ui/dialogs/compose.ui, src/Views/Search.vala
=> feat(search): advanced search dialog

data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala
=> feat(settings): old reply reminder switch

src/API/Relationship.vala, src/Views/Main.vala, src/Views/Notifications.vala
=> feat(notifications): clear

data/dev.geopjr.Tuba.gschema.xml, data/style.css, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Views/Notifications.vala, src/Widgets/Notification.vala
=> feat(notifications): dim favs and boosts in 'all' option

data/ui/dialogs/advanced_search.ui
=> fix(advanced-search): banner => label

src/Widgets/Status.vala
race condition, statuses might be ready before instance info so we cannot access tuba_can_translate yet
=> fix(status): accessing tuba_can_translate before getting instance-info

src/Services/Accounts/InstanceAccount.vala, src/Widgets/Status.vala
When available, try to get the user handle from the mentions. That might not always be available and the display name isnt available either.
#983
=> feat(status): include user tag in the 'in reply to' header

src/Views/Search.vala
This required creating a custom search entry. It's a box pretending to be an entry
#983
=> fix(search): move advanced search button in the entry

data/ui/widgets/status.ui, src/Widgets/Avatar.vala, src/Widgets/ProfileCover.vala, src/Widgets/Status.vala
=> fix(mini-profile): open on primary click

src/API/Instance.vala, src/API/Notification.vala, src/Application.vala, src/Dialogs/Composer/Completion/EmojiProvider.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala, src/Dialogs/Composer/EditorPage.vala, src/Dialogs/MainWindow.vala, src/Dialogs/ProfileEdit.vala, src/Services/Accounts/InstanceAccount.vala, src/Services/Accounts/SecretAccountStore.vala, src/Views/Conversations.vala, src/Views/Sidebar.vala, src/Widgets/Status.vala
Optional chaining, what a concept...
What optional chaining should do, is:
`nullable?.param` => `nullable != null ? nullable.param : null`
Or at least that's what I was expecting. Turns out that's not always the case. Sometimes it causes segfaults :shrug: 
Let's just get rid of optional chaining everywhere
=> feat: get rid of optional chaining

data/style.css
fix: #985
I think there are many more places to fix though I'd like feedback from those that use the hc theme
=> fix(style): use hc-able border color on fields

data/ui/views/sidebar/account.ui
=> fix(AccountSwitcherRow): do not use markup

src/Views/Notifications.vala
=> fix(Notifications): filtered banner not being visible if the state is empty

.editorconfig, data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- Admin Dashboard (#959)
- Advanced Search Dialog (#962)
- Ability to dim non-trivial notifications like favorites and boosts (#981)
- Notification clearing (#980)
- Notification filtering (#893, #995, #1014)
- Notification requests (#968)
- In-app proxy settings (#960)
- Optional Clapper support (#931, thanks [at]Rafostar)
- Replaced the Media Viewer headerbar with a floating button on fullscreen (#913)
- Reactive relationship updates (#1001)
- 'Replying to older post' reminder switch in settings (#979)
- Preview card redesign into a vertical layout (#966, thanks [at]bertob) 
- Use different icons per view for their empty state status (#964)
- New account window settings (#960, #959, #993)
- Crossed out boost icon when disabled (#965, thanks [at]jimmac)
- Custom aria labels that …
```
=> feat: v0.8.0

data/dev.geopjr.Tuba.gschema.xml, src/Services/Settings.vala, src/Views/MediaViewer.vala
=> feat(mv): graphics offload runtime setting

src/Views/MediaViewer.vala
Few small changes/enhancements for Clapper MediaViewer code:
* Enable loop for GIF videos
* Complement MPRIS args
* Do not show controls for GIFV
=> feat(mv): Few small clapper code enhancements

src/Services/Accounts/InstanceAccount.vala, src/Views/Notifications.vala
=> fix(instanceaccount): allow updating notification count more than once

src/Widgets/Status.vala
=> feat(status): name button tooltip

src/Dialogs/Admin/Report.vala
can't close the dialog because can-close is false and close-attempt is not bound
=> fix(Admin.Report): unable to close without taking action

data/ui/widgets/status.ui
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2192252
=> feat(status): menu tooltip text

src/Views/Search.vala
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2192252
=> feat(search): no query state redesign

data/style.css
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2192252
=> fix(profile-cover): focus ring stat button regression

src/Views/MediaViewer.vala
fix: #1089
Same discussion and code from the clapper cache PR applies here. We should delete all cached videos on shudown on non-clapper too
=> feat(MediaViewer): clear non-clapper on-disk cache on shutdown

src/API/Status.vala
=> fix(Status): do not hide own posts if filtered

src/Application.vala
=> feat: delete old cache mechanism leftover folder

src/Services/Accounts/InstanceAccount.vala
=> feat(InstanceAccount): handle status type

src/Dialogs/Composer/AttachmentsPageAttachment.vala
=> feat(APA): use json body instead of url params

src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/Composer/EditorPage.vala
=> feat(composer): use numeric style for counters

data/ui/views/base.ui, src/Dialogs/Composer/AttachmentsPage.vala, src/Dialogs/Report.vala, src/Views/Admin/Pages/Base.vala, src/Views/Base.vala, src/Views/MediaViewer.vala, src/Views/Profile.vala, src/Views/Timeline.vala
:-1: GtkSpinner
:+1: AdwSpinner
=> feat: Gtk.Spinner => Adw.Spinner

src/Dialogs/Composer/AttachmentsPageAttachment.vala
=> feat(APA): show thumbnail in AltTextDialog if available

src/Widgets/Attachment/Image.vala, src/Widgets/FocusPicture.vala, src/Widgets/meson.build
I can't believe I'm actually doing this...
Anyway, basically GtkPicture with focus on COVER :shrug: 
fix: #576
=> feat(Widgets): FocusPicture

src/Widgets/FocusPicture.vala
Y axis, top is 1.0, bottom is -1.0
=> fix(FocusPicture): focus-y invert

src/Application.vala, src/Dialogs/Composer/EditorPage.vala, src/Services/Accounts/InstanceAccount.vala, src/Utils/ShareHandler.vala, src/Utils/meson.build, tests/ShareHandler.test.vala, tests/WebApHandler.test.vala, tests/meson.build
`tuba://share?text=<string>&cw=[string]`
e.g. `tuba://share?text=foo%20bar`, `tuba://share?text=foo%20bar&cw=123`
fix: #908
=> feat: tuba://share

src/Dialogs/Admin/Report.vala, src/Dialogs/Admin/TakeAction.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/NotificationSettings.vala, src/Dialogs/Preferences.vala, src/Dialogs/Report.vala, src/Views/Admin/Pages/Accounts.vala, src/Views/Admin/Pages/BlockedEmails.vala, src/Views/Admin/Pages/FederationAllowlist.vala, src/Views/Admin/Timelines/BlockedIPs.vala, src/Views/Admin/Timelines/DomainAllow.vala, src/Views/Admin/Timelines/DomainBlock.vala, src/Views/Admin/Timelines/EmailDomain.vala, src/Widgets/Status.vala
=> fix: Dialog titles not following the HIG

src/Widgets/AudioPlayer/Visualizer.vala
The visualizer should not display one if animations are disabled
=> feat(visualizer): respect gtk-enable-animations

src/Views/MediaViewer.vala
=> feat(MV): copy media on ctrl+c

data/ui/dialogs/advanced_search.ui, src/Views/Search.vala
=> feat(ASD): auto-fill user handle

src/Widgets/FocusPicture.vala
=> feat(FocusPicture): only resize when necessary

data/ui/dialogs/new_account.ui
=> feat(NewAccount): done page redesign

src/Widgets/VoteBox.vala
=> feat(votebox): shorten voted

data/style.css
=> fix(style): hashtagbar hashtag

data/style.css, src/Widgets/VoteBox.vala
https://github.com/user-attachments/assets/38973349-27e5-44b7-a64e-efccb32ec513
=> feat(votebox): animations

src/Views/TabbedBase.vala
=> feat(TabbedBase): avoid nested scrolled window

data/gresource.xml, data/style-hc.css, data/style.css, data/ui/menus.ui, src/Views/ContentBase.vala, src/Views/Profile.vala, src/Views/Timeline.vala, src/Widgets/ProfileCover.vala, src/Widgets/ProfileFilterGroup.vala, src/Widgets/meson.build
Ended up stealing it from Elastic pre-1.7
=> feat(profile): better filter UX

src/Dialogs/Composer/EditorPage.vala
fix: #454 
Honestly, I don't want to be responsible for assuming the region. Libspelling seems to be able to handle it itself(?) so I'll let it decide.
The workflow is as follows:
- Keep a copy of the current default lang, which matches the host, e.g. 'en-US'
- When the language button selection changes (including when it gets first set like when replying to a post or editing your own),
- if the new selected locale is part of the original do nothing, because the original is more accurate, e.g. if the original is 'en-US' and the new one is 'en', keep 'en-US' as it has a region
- then attempt to set it as the checker language
- if it fails (e.g. if the language is not available), set the language to the original one
=> feat(EditorPage): bind spellchecking lang to post lang

data/style-dark.css, data/style.css, src/Widgets/ProfileCover.vala
Account creation birthday style :shrug: 
also finally converted almost everything to css vars from gtk vars
=> feat(ProfileCover): birthday

src/Widgets/ProfileCover.vala
fix: https://github.com/GeopJr/Tuba/pull/1205#issuecomment-2483962568
Set the style to the whole flowbox if it's the single child
=> fix(Profile): birthday style set to whole row when single

src/Dialogs/ProfileEdit.vala
follow up to #1133, wrong form data fields on profile edit
=> fix(ProfileEdit): alt text form data value

data/ui/dialogs/filter_edit.ui, src/Dialogs/FilterEdit.vala, src/Dialogs/Preferences.vala
TODO: actually test it with a working internet connection
fix: #1037
=> feat(Preferences): use navigation subpages

src/API/Account.vala, src/Views/Profile.vala
fix: #1227 
dont patch the object as it will null sources since they are from vc
=> fix(Profile): only update fields that we care about

src/Views/Search.vala
fix: #1231 
follow up to: #826
=> fix(search): uid missing

src/Utils/Host.vala
#1211 UriLauncher doesnt open file://, FileLauncher was being weird, let's add launch_default_for_uri_async back as a fallback
=> fix(Host): use launch_default_for_uri_async as a fallback

data/style.css
=> fix(style): transitions

src/API/Notification.vala
=> fix(Notifications): annual report toast year

data/dev.geopjr.Tuba.gschema.xml, src/Services/Settings.vala, src/Views/Admin/Timelines/PaginationTimeline.vala, src/Views/Home.vala, src/Views/Timeline.vala, src/Widgets/AccountSuggestions.vala, src/Widgets/LabelWithWidgets.vala, src/Widgets/meson.build
fix: #768
This is only visible if you follow <= 10 people
=> feat(Home): Account Suggestions

src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Widgets/Attachment/Item.vala
=> fix(APA): utility dialogs design

data/ui/dialogs/schedule.ui, src/Dialogs/Composer/Schedule.vala, src/Widgets/ScheduledStatus.vala
=> fix(Schedule): design

data/style.css, src/Dialogs/AnnualReport.vala
=> fix(AnnualReport): design

data/style.css, src/API/AnnualReports.vala, src/API/Notification.vala, src/Dialogs/AnnualReport.vala
=> fix(wrapped): api

data/dev.geopjr.Tuba.gschema.xml, src/API/Notification.vala, src/Application.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/Sidebar.vala
we kinda missed mastowrapped and since the only way to open it was from the notification, let's add an entry if it's December and there's a wrapped for this year
=> feat(Sidebar): fediwrapped menu item when possible

src/Views/Profile.vala
fix: https://github.com/GeopJr/Tuba/issues/1227#issuecomment-2525024348
=> fix(Profile): use active account on edit

data/style.css, data/ui/views/profile_header.ui, data/ui/widgets/profile.ui, po/dev.geopjr.Tuba.pot, src/Widgets/ProfileCover.vala
=> feat(ProfileCover): redesign ff

data/gtk/help-overlay.ui, src/Application.vala, src/Dialogs/MainWindow.vala, src/Views/Base.vala, src/Views/TabbedBase.vala
Add support for the Home key to take you to the top of the scroll window.
=> Add Home shortcut for scroll to top of page.

src/Services/Accounts/InstanceAccount.vala
Let's keep it available for January too
=> feat(wrapped): keep it for january too

src/Dialogs/ListEdit.vala, src/Views/Lists.vala, src/Views/Profile.vala
*oma only accepts json body, so lists didn't work. It now sends it as json body
=> fix(Lists): *oma

data/gresource.xml, data/ui/dialogs/notification_settings.ui, data/ui/dialogs/preferences.ui, src/Dialogs/NotificationSettings.vala, src/Dialogs/Preferences.vala
Basically move the policy settings from preferences to notifications view settings. This required moving that dialog to a ui builder file for the sake of not moving the strings to source.
Push notification settings will stay in prefs for now.
=> feat(NotificationsSettings): move policy prefs here

po/POTFILES, po/dev.geopjr.Tuba.pot, src/Widgets/ScheduledStatus.vala
=> fix: mark string as translatable

src/Application.vala
Oops, I only now noticed Brage was missing from the credits :bow:
=> feat(about): add Brage to the designer credits

src/Dialogs/FilterEdit.vala
=> fix(FilterEdit): use json instead of form data

src/Views/Thread.vala, src/Widgets/Status.vala
fix: #1263 
I need to test it on an actual connection because i only managed to test it with a local GTS instance and a real instance might be slower or inconsistent.
=> feat(Thread): refresh root status on load

src/Widgets/FocusPicture.vala
https://gitlab.gnome.org/GNOME/gtk/-/commit/a8255e32205b054425c5ba423d567fb4d922854d
=> feat(FocusPicture): bump

src/Widgets/Status.vala
=> fix(Status): convert iso timestamp to local

src/Dialogs/Preferences.vala
fix: #1280 
this feels like a regression but i dont think it is? :thinking:
=> fix(Preferences): filterrow shouldn't use markup

src/API/Instance.vala, src/API/InstanceV2.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/Bubble.vala, src/Widgets/AccountSuggestions.vala, src/Widgets/PreviewCardExplore.vala, src/Widgets/ProfileCover.vala
streamlined the api_versions too so it's easier to do future additions. Streaming should also work (if public streaming is enabled), though I couldn't test it in the devcontainer :P
=> feat(Bubble): Chuckya support

src/Views/ContentBase.vala, src/Views/Timeline.vala
=> feat(Timeline): decrease queue threshold

src/Widgets/Status.vala
=> feat(Status): allow muting if only mentioned

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build, src/Services/Accounts/InstanceAccount.vala
```md
- Chuckya support to the bubble timelines (#1285)
- Decreased new posts queue prepend scroll threshold (#1293)
- Enabled muting threads when the active user is mentioned instead of only when they are the author (#1292)
- Some filter rows being invisible due to markup (#1281)
- Default FediWrapped style being TRANSPARENT instead of WINDOW (#1282)
- Reschedule calendar month not being set correctly (#1284)
- Opening URIs on scripted exits not working due to making these functions async (#1291)
- Visual glitches and performance issues caused by the clamp and styling in timelines by switching to breakpoints (#1295)
```
=> feat: 0.9.1

src/Services/Accounts/InstanceAccount.vala
fix: #1321
Noticed some other stuff so I fixed them here:
1. devmode notification calls are triggered for all accounts, lets just handle them on active only
2. notification IDs where NOT locked to accounts and therefore a collision would be possible. (Worse that could happen would be a previous notification with the same ID to be withdrawn)
Now it should be $active-account-id-$notification-id for basic and $active-account-id-$notification-status-id-$notification-type for grouped.
TODO: maybe move both these and the notification buttons to use UUIDs for privacy? Is this needed? The grouped ones would need hashing too :////
=> feat(notifications): withdraw

src/Views/Profile.vala, src/Widgets/Status.vala
=> feat: use in-app browser for statuses and profiles

src/Widgets/LabelWithWidgets.vala, src/Widgets/RichLabel.vala
=> feat(RichLabel): middle click open external browser

src/Views/Browser.vala
fix: https://github.com/GeopJr/Tuba/issues/1334#issuecomment-2661040515
=> feat(Browser): handle create signals

src/Widgets/Avatar.vala
=> fix(Avatar): don't weak ref account

src/Widgets/HashtagBar.vala
=> fix(HashtagButton): ellipsize

src/Views/Sidebar.vala
=> feat(sidebar): quit action

data/style-hc.css, data/style.css, src/Widgets/ProfileFilterGroup.vala
Elastic's toggle groups are no longer needed as they are part of 1.7 now.
=> feat(ProfileFilterGroup): use AdwToggleGroup

src/Application.vala, src/Dialogs/Composer/Dialog.vala, src/Views/ScheduledStatuses.vala
=> feeat(ScheduledStatuses): refresh on new post

data/ui/views/profile_header.ui, data/ui/widgets/announcement.ui, data/ui/widgets/status.ui, src/Dialogs/MainWindow.vala, src/Widgets/Attachment/Box.vala, src/Widgets/HashtagBar.vala, src/Widgets/ProfileCover.vala, src/Widgets/Status.vala, src/Widgets/Status/ReactionsRow.vala
A lot to fix and test still but a big step forward.
WrapBox is not a replacement for FlowBox, but it highlighted parts we can rethink, like the media box.
At least now we have these awesome layouts, instead of the flowbox abuse:
=> feat: wrapbox

src/Dialogs/Composer/AttachmentsPageAttachment.vala
=> feat(AttachmentsPageAttachment): use preview url for videos if available

src/Views/Notifications.vala
=> feat(Notifications): clear on scroll to top

src/Services/Settings.vala
=> feat(settings): make proxy instany apply

src/Application.vala
=> feat(Application): apply settings on window close when work-in-background is enabled

data/style.css
:thinking: not sure
Tuba has many styles, most of the time I fine-tuned the border radii to the appropriate padding-based values but now it's a bit difficult to know what elements should change, considering cards stayed the same but everything else changed...
=> feat(style): tiny adw 1.8 roundness changes

src/Application.vala
=> feat(Shortcuts): add Ctrl+L for search

data/style-dark.css, data/style-hc.css, data/style.css, src/API/GroupedNotificationsResults.vala, src/Widgets/GroupedNotification.vala
=> fix(grouped): style

data/ui/views/profile_header.ui, data/ui/widgets/profile.ui, meson.build, src/Widgets/Account.vala, src/Widgets/ProfileCover.vala
=> fix(Avatar): size on libadwaita 1.7.5

src/Dialogs/Composer/AttachmentsBin.vala, src/Dialogs/Composer/Dialog.vala, src/Widgets/Status.vala
fix: #1310 
fix: #1457
Delete & Redraft existed internally already but we could make it an option when deleting. I merged it with Edit since they are pretty much the same but 1-2 variables.
There are some decisions that need to be taken before merging so draft for now
=> feat(status): delete & redraft

data/dev.geopjr.Tuba.gschema.xml, src/API/Tag.vala, src/Dialogs/Composer/Polls.vala, src/Services/Settings.vala, src/Views/Search.vala
=> feat(search): history

src/API/Relationship.vala, src/Views/Profile.vala
pre api 6 mastodon used pin/unpin
=> fix(Profile): endorse endpoint for < 6

src/Widgets/FadeBin.vala
=> fix(FadeBin): overflow hidden

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Helpers/Image.vala, src/Views/Timeline.vala
Controversial
1. re-organized the settings to more descriptive groups instead of a huge 'appearance' one
2. removed some settings from the GUI
3. added summaries and descriptions to dconf
4. changed some defaults
---
Tuba had a lot of... advanced? settings that we could do without. This is a multi-part effort.
Hide unpopular settings from the GUI.
- Color scheme: I can only assume that the people who set it to anything but `system` (which is mostly set to `dark` when done), is because they use desktops that don't support the xdg standards. Please ask your desktop to support it in that case. That setting wasn't meant to substitute that, but to provide a way to use a different one than the system (which is useful for example in book reading apps at night)
- Blurhash: turning it off is very …
=> feat(Settings): rehaul

data/dev.geopjr.Tuba.gschema.xml, src/Dialogs/Composer/Attachment.vala, src/Services/Settings.vala, src/Views/Drive.vala
Setting to disable exif metadata alt text extraction when uploading attachments
=> feat(settings): ability to disable alt text extraction

src/Services/Accounts/InstanceAccount.vala, src/Views/Profile.vala
=> fix(Profile): pleroma and < 4.4.0 endorsements

src/Views/EditHistory.vala, src/Views/FollowRequests.vala, src/Views/Hashtags.vala, src/Views/Lists.vala, src/Views/NotificationRequests.vala, src/Views/NotificationRequestsList.vala, src/Views/ScheduledStatuses.vala, src/Views/Timeline.vala
fix: #1432 
This introduces a min batch size in select timelines. Tbh I think we need to rethink the whole think with updating infinite timelines, but will do for now.
=> feat(Timeline): use a batch min value property

src/Widgets/HashtagBar.vala, src/Widgets/Status.vala
=> feat(Composer): allow showing all hashtags in hashtagbar

data/ui/dialogs/schedule.ui, src/Dialogs/Composer/AttachmentsBin.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/PreferredSizeBin.vala, src/Dialogs/Composer/Schedule.vala, src/Dialogs/Composer/meson.build
Sets the follows-content-size composer dialog subpage sizes to the same size as itself (though a set natural size bin widget)
todo:
- leak test
=> feat(composer): preferredsizebin

data/style.css, data/ui/widgets/status.ui
=> fix(style): fadebin button

src/Services/Accounts/SecretAccountStore.vala
=> fix(SAS): DONT_MATCH_NAME again
