src/Application.vala
Small fix. Currently, the window when being resized looks a little laggy, this MR makes it look faster. 
To implement this, the settings service saves its changes until the application is closed, instead of saving them when any property is changed, which makes in general the tweaking of settings in the preferences window slightly faster too.
=> Slightly faster window resizing

data/ui/dialogs/main.ui
The slide transition reveals the lack of separator between the pages and the headerbar border, which looks odd. The over transition fixes that. Also the slide transition doesn't denote a back gesture as well as the over transition.
=> main: Use the over transition for the leaflet

data/ui/views/sidebar/view.ui
Sometimes the text in sidebar header is wrapped even if there is room for the text. This PR expands the text box and adds a slight vertical padding to make the layout a bit more neat.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot from 2023-01-07 14-20-48](https://user-images.githubusercontent.com/20158357/211145993-66582840-6b1e-48b6-b070-5d13421a5611.png) | ![Screenshot from 2023-01-07 14-20-31](https://user-images.githubusercontent.com/20158357/211146012-67fa61f4-f129-4993-a09a-99d4eeea0f91.png) |
=> Fix header text wrapping in sidebar

data/style.css, data/ui/views/profile_header.ui, data/ui/widgets/status.ui, data/ui/widgets/votebox.ui, src/Utils/DateTime.vala, src/Views/Profile.vala, src/Widgets/VoteBox.vala
This PR fixes minor inconsistencies in the app's layout to improve its overall appearance.
**Profile view:**
- Increase the cover image's border radius
- Increase the stat row's height
- Disable activation of the note row
**Status widget:**
- Center the indicator box vertically
**Poll widget:**
- Make the widget flatter
- Move percentage to the row subtitle
**DateTime utils:**
- Prevent `humanize()` and its derivatives from producing double spaces (`Jan  6` -> `Jan 6`)
=> Minor visual tweaks

data/style.css, data/ui/dialogs/new_account.ui, src/Dialogs/NewAccount.vala, src/Services/Network/Network.vala, src/Services/Network/Request.vala
This PR makes the following changes to the dialog:
- Flatten the header bar
- Replace vanilla `Gtk.Entry` widgets with their `Adw.EntryRow` variants
- Change wording on some screens
- Hide the auth token entry unless manual authorization is explicitly requested by the user
- Fix the Network service so that error messages are properly passed to the dialog
| Before  | After |
| ------------- | ------------- |
| ![Screenshot from 2023-01-09 22-24-04](https://user-images.githubusercontent.com/20158357/211380508-61e6ef86-2e03-4f5f-9d2f-38d6ba86ae81.png)  | ![Screenshot from 2023-01-09 22-23-52](https://user-images.githubusercontent.com/20158357/211380552-cd64de27-2028-4b3d-b629-4079dbf4d9c0.png)  |
| | ![Screenshot from 2023-01-09 22-38-44](https://user-images.githubusercontent.com/20158357/211 …
=> Refactor Add Account dialog

.github/workflows/build.yml, data/meson.build, dev.geopjr.tooth.Devel.json, install.sh, meson.build, meson_options.txt, src/Application.vala, src/Build.vala.in, src/Dialogs/MainWindow.vala
This PR adds a `profile` option to the meson configuration. If is set to `development` during compilation, the app will:
- Add `.devel` class to the main window
- Use alternative nightly icon
- Modify About dialog to display branch name and revision hash instead of a version (which makes sense in production builds only)
Additionally, a development Flatpak manifest is added with [Vala SDK](https://github.com/flathub/org.freedesktop.Sdk.Extension.vala) enabled for syntax highlighting in GNOME Builder.
=> Add meson profiles

data/style.css, data/ui/widgets/status.ui, src/Widgets/Status.vala
actions should always be at the bottom, but if there are no actions, there should be bottom padding
additionally, thread line (middle, end) has to reach the previous member
fix: #84
=> fix(status): padding

src/API/Attachment.vala, src/API/Relationship.vala, src/API/SearchResults.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/NewAccount.vala, src/Services/Accounts/AccountStore.vala, src/Services/Accounts/InstanceAccount.vala, src/Services/Accounts/SecretAccountStore.vala, src/Services/Network/Network.vala, src/Services/Network/Request.vala, src/Views/FollowRequests.vala, src/Views/Hashtag.vala, src/Views/Lists.vala, src/Views/Profile.vala, src/Views/Thread.vala, src/Views/Timeline.vala, src/Widgets/Status.vala, src/Widgets/StatusActionButton.vala, src/Widgets/VoteBox.vala
fix: #192 
During the libsoup3 migration we switched to inputstreams. The main issue is that once read it cannot be reused. This PR adds a parser parameter to supply our own parser instead of creating a new one. Additionally since all the array network functions were using the same code from `get_array_mstd`, I just made them call it.
I'm leaning towards making them use a user-provided parser only and get rid of handling inputstreams directly.
=> fix(network): re-use functions and parsers

src/Views/MediaViewer.vala
It's better to match Loupe's design and functions so users have a familiar experience between them:
Loupe:
Progress so far:
(pagination buttons are only visible if there are more than 1 items in the carousel)
=> feat(media_viewer): match loupe

data/ui/views/base.ui, src/Views/Base.vala, src/Views/ContentBase.vala, src/Views/Search.vala, src/Views/TabbedBase.vala, src/Views/Thread.vala, src/Views/Timeline.vala
fix: #145 (again)
1/2 of #204 
The network status / message view was messy since it had 3 different properties that had to change the view and keep track of the other widgets and sub-stacks (e.g. if the title was set, it had to change the sub-stack to "message" and check if there's a "message" (and whether it's empty) etc etc etc)
It's now a bit easier to maintain by setting `status` to `StatusMessage?`
(should probably be renamed from `status` to something else as it might conflict with fedi's statuses)
=> feat: refactor net status view

src/Services/Accounts/InstanceAccount.vala, src/Services/Network/Streamable.vala, src/Views/Conversations.vala, src/Views/Home.vala, src/Views/List.vala
Several streaming bugs and disabled features:
- Stream conversations
- Connect to all accounts' notifications and NOT `user` - this will save bandwidth
- fix: #131 - when unsubscribing, `get_stream_url` might have already changed (or rather return null) so instead use `t_connection_url`
=> fix(network): streaming

src/Views/ContentBase.vala, src/Views/Timeline.vala
fix: #126
- If the user's scroll position is near the top: new posts get prepended
- If the user's scroll position is not near the top: new posts get added into an array and when the user scrolls to near the top, they get prepended
=> feat(Timeline): entity queue

src/Views/ContentBase.vala, src/Views/Profile.vala, src/Views/Timeline.vala
This (when it's done) + #232 should fix: #182
The lag on refresh is not really a network issue, but rather a widget creation one.
As of now, I migrated ListStore #insert => #splice (which is more efficient).
~~What I want to try is using threads or~~ attempting to convert more sync operations to async before marking as ready
=> fix(Timeline): refresh performance

data/dev.geopjr.Tuba.gschema.xml, data/style.css, data/ui/dialogs/preferences.ui, src/API/Entity.vala, src/API/PeerTube.vala, src/API/PeerTube/File.vala, src/API/PeerTube/Resolution.vala, src/API/PeerTube/StreamingPlaylist.vala, src/API/PeerTube/meson.build, src/API/Poll.vala, src/API/Status.vala, src/API/Status/PreviewCard.vala, src/API/Status/meson.build, src/API/meson.build, src/Dialogs/MainWindow.vala, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Views/MediaViewer.vala, src/Views/Timeline.vala, src/Widgets/Status.vala
Cards :sparkles: 
link:
video:
clicking on a card will show a dialog since it's an out-of-instance request and users should confirm for privacy reasons:
PeerTube :octopus: 
PeerTube videos should now play on the built-in media viewer
:information_source: qualities higher than 720p become laggy on my machine (gstreamer backend, I haven't tested on ffmpeg) so I set some limits (720, 480, 360 are preferred unless they are not available)
Similarly, PeerTube videos require out-of-instance requests and a similar dialog shows up:
fix: #244 
edit:
there's an option in settings to disable cards
=> feat(status): cards & peertube viewer

src/API/Account.vala, src/API/SearchResults.vala, src/API/Tag.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Services/Network/Request.vala, src/Views/Lists.vala
fix: #246 
Let's just encode all params on exec instead of when constructing requests since we missed some more than once
=> fix: encode all params on exec

src/Application.vala
This reverts commit 491c28f70c4417f04532ddfc6a724919e5d01167.
fix: #267
unfix: #197
=> revert: "fix: missing underline on some links"

src/API/Status/PreviewCard.vala, src/Application.vala
This was preventing preview on BW instances that changes the title (e.g. https://velhaestante.com.br/book/11624/s/the-name-of-the-wind ).
The regular expression used here is the same one used by BW itself (see [BOOK_PATH][bw-path], [SLUG][bw-slug], and [full path][bw-view]).
[bw-slug]: https://github.com/bookwyrm-social/bookwyrm/blob/ee1dd612fb223bf44f98026b8f42991cff97279f/bookwyrm/utils/regex.py#LL9C10-L9C34
[bw-path]: https://github.com/bookwyrm-social/bookwyrm/blob/ee1dd612fb223bf44f98026b8f42991cff97279f/bookwyrm/urls.py#L26
[bw-view]: https://github.com/bookwyrm-social/bookwyrm/blob/ee1dd612fb223bf44f98026b8f42991cff97279f/bookwyrm/urls.py#L649
=> fix(bookwyrm): do not rely on title for bookwyrm detection

src/Services/Accounts/InstanceAccount.vala, src/Views/Notifications.vala
fix: #285 ?
A needed refactor after the websocket one. Notification view is now responsible for streaming notifications rather than the account.
~~TODO:~~
~~cleanup before merging~~
=> refactor(View): Notifications

src/Dialogs/Composer/Dialog.vala
Currently when sending a post, the dialog does not change. This allows the user to accidentally press "Publish" or use one of the accelerators to send the post again. It's also just not good feedback on whether the post is sending.
This commit changes the dialog such that once the publish process begins, the "Publish" button, composer pages (edit/attach/poll), and on_commit () callback are all disabled until the commit transaction fails.
---
I didn't create an issue for this because I felt it would be a good opportunity to learn a bit of Vala/Adwaita if I tackled this myself, please let me know if you have feedback 🙏️
=> fix: set composer dialog widgets to insensitive when publishing

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Utils/Host.vala, src/Utils/Tracking.vala, src/Utils/meson.build
ported from https://source.puri.sm/Librem5/chatty/-/merge_requests/1229
draft until it's merged on Chatty
=> feat: remove tracking ids from links

data/style.css
=> feat(video): increase padding on controls

src/API/Tag.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala
=> feat(composer): show weekly use on tag

.gitignore
When building the app with `flatpak-builder`, a `.flatpak-builder/` directory is created for the build environment.
_Since (afaik) build directories/environments shouldn't be pushed to repositories, it would be logical to add this exception._
<sub>This is my first pull request, please let me know if I did anything wrong; any and all criticism is very much appreciated!</sub>
=> fix: add .flatpak-builder/ directory to .gitignore

data/style.css, data/ui/widgets/status.ui, src/Widgets/Emoji.vala, src/Widgets/EmojiLabel.vala, src/Widgets/LabelWithWidgets.vala, src/Widgets/RichLabel.vala
1. headings (x boosted / favourited / etc) were some pixels to the right (button + padding + box spacing) but now should match the name label, label being in the same column as the status content
2. name labels with emojis were some pixels higher than the handle due to the emoji. Fixing it is a bit hacky but it works: increase line height to 1.8 and negative padding vertically to decrease the size of the button
=> fix(Status): name label styling

src/Utils/Html.vala
*oma uses newlines, Pixelfed uses both `<br />` and newline at the same time
only remove newlines if there are br's
=> fix(HtmlUtils): do not remove newlines if there are no brs

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Widgets/Attachment/Image.vala
Adds a setting to letterbox media instead of stretching and cropping (cover). This is especially important for art communities as viewing the full image in attachments is generally preferred over cover.
=> feat(Image): letterbox setting

src/Widgets/LabelWithWidgets.vala
when for_size is -1 Tuba freezes, ~instead set it to 0~ setting it to 0 causes headings to have incorrect width, instead set it to the last HORIZONTAL for_size when the VERTICAL for_size is -1 :shrug: 
fix: #352 
TODO: more testing
=> fix(LWW): measure + for_size == -1

build-aux/dev.geopjr.Tuba.Devel.json, meson.build, src/Dialogs/Composer/EditorPage.vala
gspell-4 is still available as a fallback
The only difference I noticed (apart from some UI) is that your cursor needs to be on the word you are looking suggestions up for.
cursor next to word:
cursor in word:
:warning: If GtkSourceView is missing, then only gspell-4 is available
=> feat: libspelling support

src/Widgets/VoteBox.vala
Poll option titles can currently be interpreted as html, causing them to be displayed incorrectly at times. This is inconsistent with other Mastodon/ActivityPub clients. All documentation on how poll options should be formatted also seems to point to them only ever being plain text.
This small change escapes characters that can be interpreted as markup when rendering polls.
Before:
After:
=> fix: Escape markup in poll options

src/Views/MediaViewer.vala
[Screencast from 2023-07-12 13-56-01.webm](https://github.com/GeopJr/Tuba/assets/18014039/be384bb8-d99b-4815-b33b-34e2e5c5dc86)
=> feat(MediaViewer): media_buttons revealer

data/dev.geopjr.Tuba.appdata.xml.in, meson.build
Hopefully I didn't miss anything
```
- Decrease sidebar width (#280, thanks [at]bertob)
- Explore tab (#294)
- Smaller icons for indicators (#217, thanks [at]jimmac) 
- Autoplay videos
- Keep follow requests tab always visible
- Small app version easter egg based on current day's events
- Confirm action on inform dialogs
- Pull to refresh (#283)
- Composer poll page (#307)
- More keyboard shortcuts (#303)
- Handle code elements in posts
- Make composer insensitive after publishing (#311, thanks [at]VictoriaLacroix)
- Bump LabelWithWidgets (thanks [at]zecakeh)
- Custom emoji picker (#308)
- Remove tracking ids from links (#305, thanks [at]kop316)
- Keyboard shortcuts tab & window
- Increase padding on video controls (#322, thanks [at]bertob)
- Preview card design changes in posts (#325, …
```
=> feat: v0.4.0

src/Widgets/PreviewCard.vala
=> fix(PreviewCard): discussed label alignment

po/dev.geopjr.Tuba.pot, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Widgets/Attachment/Item.vala
=> fix: mark alt text dialog titles as translatable

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- Error dialogs on errors during on_commit for the composer
- Hide CustomEmojiChooser button when there are no emojis available
- 'Discussed' label not filling up the full available width of PreviewCards used in the News tab (#400)
- Marked alternative text dialog titles as translatable (#394, thanks [at]LukaszH77)
- Sidebar having horizontal overflow due to some strings in some languages being too long by ellipsizing them (#403)
- Renamed appdata file to metainfo per spec (#416, thanks [at]carlwgeorge)
- Validate metainfo with `--nonet` for environments without a network connection (#416, thanks [at]carlwgeorge)
- CustomEmojiChooser not dismissing on Esc
- Compiling without GtkSourceView
- Compiling with GTK < 4.10
- Not being able to save the `work-in-background` setting due to …
```
=> feat: v0.4.1

src/Widgets/Status.vala
seen on #480
application label seems to be affected by the large font setting when it shouldn't(?) or at least should be the same as the date label
=> fix(Status): expanded application label large font setting

data/style.css, data/ui/widgets/announcement.ui, data/ui/widgets/status.ui, src/API/Tag.vala, src/Views/ContentBase.vala, src/Views/Lists.vala, src/Widgets/PreviewCard.vala
Let's assume that all listview items are cards with card-spacing instead. This sets the styles on the listviewitemwidgets instead of the children
edit: it also makes them hide the overflow as the threadlines would slightly overflow
=> fix(ContentBase): ListView items style

src/Views/ContentBase.vala, src/Views/Timeline.vala
Entity queue was introduced on #234 as a workaround for ListBox's constant vadjustment change when new items got added to the list by only appending them when the user was near the top. ListView doesn't have this issue.
ContentBase's reached_close_to_top signal got commented out as it's unused.
=> feat: remove Entity Queue

data/ui/widgets/status.ui, src/Widgets/LabelWithWidgets.vala
During the ListBox -> ListView migration the name label had to no longer wrap. Ellipsizing doesn't exactly work as expected on LWW so it caused overflows. After correctly setting up the AdwClamp with the ListView, it no longer seems to be an issue so we can revert back
=> fix(Status): overflow on large names

src/API/Attachment.vala, src/API/Status/PreviewCard.vala, src/Application.vala, src/Services/Cache/AbstractCache.vala, src/Services/Cache/BlurhashCache.vala, src/Services/Cache/meson.build, src/Utils/Blurhash.vala, src/Utils/meson.build, src/Widgets/Attachment/Image.vala, src/Widgets/PreviewCard.vala, tests/Blurhash.test.vala, tests/meson.build
fix: #487 
This is a pure Vala blurhash decoding implementation inspired by https://github.com/woltapp/blurhash and https://github.com/mad-gooze/fast-blurhash/.
FAQ:
- Q: Why not use the 'official' library?
- A: It's unoptimized (for example, it calculates sizeFlag, numX, numY and size twice, once for the validation check and then for the decoding again). Additionally, by writing it in pure Vala it makes use of Glib (and lets Vala handle the memory).
- Q: Why does it not match the 'official' library's results 1:1?
- A: It uses parts of `fast-blurhash`'s algorithm, which is (or at least should be) faster but has slightly different results.
TODO:
- ~~unit tests~~
- ~~actually use them~~
- ~~move the pixbuf -> paintable part into its own function?~~
=> feat(Utils): blurhash

src/Utils/Blurhash.vala, tests/Blurhash.test.vala
Partial base83 decoding should handle > str.length. Returning 0 would produce wrong blurhashes, they should now be closer to the official library's.
=> fix(Blurhash): wrong partial base83 decoding

src/Utils/Blurhash.vala
valac complains about an unused function otherwise (even though it's being used)
=> chore(Blurhash): make the class public

src/Widgets/MarkupView.vala
Akkoma & other backends that support quotes wrap the "RE: <quote url>" footer in a span with the class `quote-inline` so clients that support quotes remove it:
Before:
After:
=> feat(MarkupView): hide quote url

src/Services/Accounts/InstanceAccount.vala
They are not and probably cannot be properly grouped without getting the full context of the status
=> feat: remove mentions from grouped notifications

src/Views/Main.vala, src/Views/TabbedBase.vala
fix: #518
Surprisingly more complex than I thought it would be, we want it to be visible as long as is_mobile is false but the breakpoint that sets it  can get triggered on desktop too, so instead create a virtual property and override it on Main so it only modifies it on mobile
=> feat(views main): headerbar titles

data/ui/dialogs/compose.ui, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/EditorPage.vala
- Uses the adw 1.4 widgets + breakpoints
- Sets the title
- fixes the composer overflowing when content types are available by hiding the dropdown arrows
=> feat(Composer): adw 1.4 + hide arrows when overflowing

src/Views/MediaViewer.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala
fix: #524
This is a bit messy:
- copying attachments (outside of media viewer) will need to first download the full image
- you can only copy images
- the action will only be visible on image
(Tuba's media viewer can load multiple formats (videos, audio, remote audio) so the above is necessary)
=> feat(Media): copy to clipboard action

meson.build, src/Application.vala, src/Dialogs/DevConsole.vala, src/Dialogs/MainWindow.vala, src/Dialogs/meson.build, src/Services/Accounts/InstanceAccount.vala, src/Services/Network/Streams.vala, src/Services/Settings.vala, src/Views/Home.vala, src/Views/Notifications.vala
Taking screenshots for the stores is awfully tedious, I usually run a Mastodon instance, create accounts, set them up, create the relationships, create the posts and quickly take screenshots. With DEVMODE, there's a special dialog that allows you to set some stuff up and push custom entities
=> feat: DEVMODE

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, CODE_OF_CONDUCT.md, README.md, Tuba.doap, data/dev.geopjr.Tuba.metainfo.xml.in, meson.build, vala-lint.conf
- Simplify issue templates: no need for all the checkboxes in feature requests, bug trubleshooting info is not longer required as some bugs are about the app not starting or really unneeded, bug logs section clarification on how to get logs now that message logs became debug
- Move to GNOME's CoC in preparation for Circle
- README badges colors changed to the non-blue icon
- doap platform clarification
- metainfo contact link
- lint ignore line length
=> chore(metadata): bump

data/gtk/help-overlay.ui, src/Application.vala
Per the [HIG](https://developer.gnome.org/hig/reference/keyboard.html), Ctrl+comma should open the Preferences.
=> feat: add shortcut for Preferences

data/ui/dialogs/list_edit.ui, src/API/List.vala, src/Dialogs/ListEdit.vala
Mastodon 4.2.0 added a setting for lists to hide members' posts from the home timeline.
Needs further testing on non-supported versions (and probably hide it then?)
=> feat(ListEdit): hide posts from home

src/Views/Sidebar.vala
- account switched is called after account**s** switched, causing the selection to not update then
- the popover would stay open on forget requiring an extra click to first dismiss it and then answer the modal
- removing the rows manually is messy, instead use a model
=> feat(account_switcher): improvements

src/API/Account.vala, src/API/Account/Source.vala, src/API/Announcement.vala, src/API/BookWyrm.vala, src/API/Conversation.vala, src/API/Entity.vala, src/API/Funkwhale.vala, src/API/Instance.vala, src/API/Instance/Mastodon/Configuration/MediaAttachments.vala, src/API/PeerTube.vala, src/API/PeerTube/StreamingPlaylist.vala, src/API/Pleroma/Status.vala, src/API/Poll.vala, src/API/SearchResults.vala, src/API/Status.vala, src/API/Status/PreviewCard.vala, src/API/Tag.vala, src/Widgets/VoteBox.vala
ArrayList deserialization from JSON has been very messy. There's a huge switch statement that goes through each possible property name to find the type. Not only is that unmaintainable but also leads to property conflicts:
For example an entity that has an `uploads` property of string and an entity that also has an `uploads` property but of API.Attachment **cannot** co-exist. We've been lucky so far that there haven't been any conflicts.
This PR creates a virtual function that returns a `Type` for a property name, allowing descendants to override it for their needs.
=> feat(Entity): OOP-ify the array deserialization mess

data/style.css, data/ui/views/profile_header.ui, src/API/Account.vala, src/API/Account/Role.vala, src/API/Account/meson.build, src/API/Entity.vala, src/Widgets/ProfileCover.vala
Mastodon 4.2.0 added profile badges
(Most instances will have 1-2 badges at most)
The style is mostly from PikaBuckup. The API returns a color for each badge/role but we will ignore it has the same issues as the freedesktop accents - a11y etc. Best we can do is find the closest adwaita color :shrug: Mastodon web also ignores it.
Design wise, mastodon web has an icon next to the labels but it gets repetitive. Mastodon web also moved the automated/bot icon/badge(?) there too, I don't think we should move tubas.
The badge background could change to a transparent accented one.
=> feat(profile): role badges

.github/workflows/build.yml
gnome-sdk now has libadwaita 1.4
=> feat(ci): re-enable snap

src/Views/Profile.vala
the focus on the listboxrow did not follow the card's borders. Instead of setting the cover to card and card-spacing, set the row
=> fix(profile): cover focus style

data/style.css
fix: #581 
Apparently ListRow's activatable hover background-color ends up overriding .card's :shrug:
=> fix(status): row + card bg color

src/Views/Main.vala, src/Views/TabbedBase.vala
fix: #575 
The workflow is unnecessarily complex. On narrow mode, the ViewSwitcher should be the headerbar child and the Base breakpoint should handle its visibility BUT on wide mode, the WindowTitle should be the headerbar child and the Base breakpoint should not touch it at all. Instead of changing the headerbar child, set it to a stack and change the page. On `Main` specifically, the page can be set to switcher ONLY when it's on narrow mode
=> fix(Main): headerbar conditions

data/gresource.xml, data/style.css, data/ui/dialogs/main.ui, data/ui/views/media_viewer.ui, src/API/Status/PreviewCard.vala, src/Dialogs/MainWindow.vala, src/Views/MediaViewer.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/ProfileCover.vala, src/Widgets/ScaleRevealer.vala, src/Widgets/meson.build
Ported ScaleRevealer from Fractal
Very WIP as the way the media viewer is displayed changed. The style difference in the recording is not on purpose. Media Viewer API needs a refactor asap.
The animation looks really nice!
https://github.com/GeopJr/Tuba/assets/18014039/05b0e615-fbc1-433e-922e-3654e97b0549
TODO:
- ~~Refactor media viewer~~ kind-of
- ~~add comment~~
- ~~add other animations~~
- ~~make sure the mediaviewer headerbar follows the animation~~
- ~~swipe opacity of floating buttons and carousel indicator dots~~
=> feat(MediaViewer): ScaleRevealer

data/ui/menus.ui
The share icon is more commonly associated with opening a share sheet and with no visual feedback of a successful copy, it can look like the button did nothing.
Ideally, the copy action would display a toast too.
=> Use copy icon for copying handle

src/Dialogs/MainWindow.vala, src/Views/MediaViewer.vala, src/Widgets/ScaleRevealer.vala
MediaViewer animation should play based on the current carousel position aka if you open the first image and scroll to the 3rd, dismissing the media viewer should play the animation for the third image
https://github.com/GeopJr/Tuba/assets/18014039/6760dc9e-246c-4d00-965f-240fb21202d3
TODO:
- ~~fix some snapshot issues~~ fixed, a wrong texture is better than the child's texture
=> feat(ScaleRevealer): multiple widgets

data/ui/dialogs/main.ui, src/Application.vala, src/Dialogs/MainWindow.vala, src/Services/Network/Network.vala, src/Views/MediaViewer.vala, src/Views/Profile.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/Status.vala
fix: #618 
not sure where else to use them:
- Copied handle
- Copied url
- Copied media
- Saved media
- Errors (no timeout)
=> feat: global toast feedback

src/Views/ContentBase.vala, src/Views/Profile.vala, src/Views/Timeline.vala
fix: #635 
On profiles we need to keep the first item when refreshing (req for ListView), but we didn't clean up the API after before refreshing as clean () was no longer Timeline's
=> fix(Profile): timeline api not being reset

src/Application.vala
GTK_THEME is not the proper way to theme your desktop. It breaks many of Tuba's widgets.
If you want to theme your desktop use themes that use `~/.config/gtk-4.0` or [Gradience](https://gradienceteam.github.io/).
=> feat: drop GTK_THEME

src/Widgets/PreviewCard.vala
A css class was missing on the image when there is no preview
=> fix(PreviewCard): image border radius

src/API/Status/PreviewCard.vala, src/Application.vala, src/Dialogs/Composer/Dialog.vala, src/Services/Accounts/SecretAccountStore.vala, src/Views/Lists.vala, src/Views/Profile.vala, src/Views/Sidebar.vala, src/Widgets/Status.vala
feat: use pango markup for the forget dialog
The question API was just a MessageDialog constructor, forcing its users to destroy dialogs manually and handle responses. Since the response will always be yes/no and MessageDialog added a choose method, we should turn it into a proper async helper that returns a bool based on the response and handles everything else.
Other goodies include a skip parameter that can be used with preferences to skip the dialog altogether (the goal is to avoid duplicate code) (that can be used with #666), use_markup on body and heading (can be provided to the struct) and clearer API.
The main downside is that async and structs can't use default parameter values so everything must be provided on every instance (e.g. the skip parameter)
TODO:
- check if composer is …
=> feat: refactor question api

meson.build, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/Composer/EditorPage.vala, src/Dialogs/ProfileEdit.vala
gspell 4 support requires a beta version of gspell with some additional patches of mine which can be found here https://github.com/geopjr-forks/gspell-4
I don't think anyone is using it. libspelling is maintained, shipped in distros and doesn't require additional patches, so I think it's ok to remove gspell-4 support.
=> feat(composer): remove gspell-4 support

src/API/Status/PreviewCard.vala, src/Application.vala, src/Dialogs/Composer/Dialog.vala, src/Services/Accounts/SecretAccountStore.vala, src/Views/Lists.vala, src/Views/Profile.vala, src/Views/Sidebar.vala, src/Widgets/Status.vala, src/Widgets/Status/ActionsRow.vala
In #672 the question API changed to return a bool, true for yes, false for no. However I completely missed the close response, sent when the user closes the dialog without choosing one of the responses. It would be treated as choosing the "No" one, but that shouldn't always be the case. This PR changes the question API to return an enum value of YES, NO, CLOSE with the helper instance methods truthy (YES) and falsy (NO, CLOSE)
fix: #689
=> feat(Question): handle close responses

data/ui/widgets/votebox.ui, src/Widgets/VoteBox.vala
These labels can in theory become arbitrarily long due to translation. Thus, its width should be controlled using ellipses. This is as of now an issue with the German translation.
Fixes: https://github.com/GeopJr/Tuba/issues/665
=> fix(votebox): ellipsize vote count and expiration label

src/Services/Accounts/AccountStore.vala, src/Services/Accounts/InstanceAccount.vala, src/Services/Accounts/SecretAccountStore.vala, src/Services/Settings.vala
Partially ripped out of #638 
It has a fallback so logins don't get removed
=> feat(secretaccount): use uuids

data/dev.geopjr.Tuba.gschema.xml, src/Application.vala, src/Services/Accounts/SecretAccountStore.vala, src/Services/Settings.vala
I think it'd better to merge after #638 even if partially merged
fix: #554 
Relocatable schemas are very undocumented and very underused
=> feat(Settings): per account

src/Services/Network/Request.vala, src/Utils/Host.vala
it should now cache videos under tuba/manual/media/ only.
The previous behavior was caching it under tuba/<url>/ *and* tuba/soup/misc/ (soup's cache)
=> feat(Host): use proper pathing and caching

src/Services/Accounts/SecretAccountStore.vala
To fix #114 we decided to do #134
Upon further usage of libsecret and further understanding of its internals, that's a terrible idea. Instead of just searching for the dev.geopjr.Tuba secrets, it looks up ALL of them that match the other attributes (version=1,login=\*). That can lead to other non-tuba secrets getting both read and parsed by tuba.
Ultimately, we need to revisit #114 and figure out why the `xdg:schema` did not match tuba's.
=> feat(SecretAccountService): do not read all secrets

src/Dialogs/Composer/Completion/CompletionProvider.vala
fix: #705 
Also fixed other word ending characters being replaced (`@masto.` => `@mastodon `)
=> fix(CompletionProvider): do not move forward on word or line end

src/Views/Search.vala
Mastodon's web ui limits the "All" tab to 4 items per category (4 people, 4 hashtags, 4 posts) and shows everything on each category. That sounds good to me
Also it orders them as People > Hashtags > Posts. I changed it so Tuba does the same, that way hashtags separate people and posts since they look similar-ish. (Tuba does however place hashtags at the top if the search query starts with `#`)
=> feat(Search): limit All to 4 per category

src/API/Status/PreviewCard.vala
fix: #582 
close: #666 (for now)
Upon further discussion, removing it altogether seems like the best approach
=> feat(PreviewCard): remove dialog

src/Widgets/RelationshipButton.vala
The intermediate state that a RelationshipButton implicitly has is not displayed to the user. As the button can be in this state for up to the timeout of the corresponding network request, it can lead to a perceived unresponsiveness of the app.
I also tried a Gtk.Spinner, but to me, it looks like a label fits better the button that also has a label otherwise.
=> feat(RelationshipButton): add feedback to transitional loading state

README.md, data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
release note:
```
- Keyboard shortcut for preferences (#549, thanks [at]TheEvilSkeleton) 
- Removed `.view` styling from the composer (#551, thanks [at]bragefuglseth)
- Open in Browser for profiles (#563)
- Option to hide accounts in lists from the Home timeline (#557)
- Automatically close the account switcher popover when selecting "Forget" (#562)
- `web+ap` support (#561)
- Subscribing for notifications on new account posts (#568)
- Profile role badges (#555)
- Composer button always visible on wide sizes (#552, thanks [at]bragefuglseth)
- Update the preview card's icons and colors (#584, thanks [at]bertob)
- Keep track of the window's maximized state between restarts (#593, thanks [at]henryrov)
- Transition when entering and leaving the MediaViewer (#602, thanks Fractal Team)
- …
```
=> feat: v0.6.0

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
fix: #714 
```
- French translation having being replaced by another language by mistake (#715, thanks [at]rene-coty) 
**Full Changelog**: https://github.com/GeopJr/Tuba/compare/v0.6.0...v0.6.1
```
=> feat: v0.6.1

src/Dialogs/Composer/EditorPage.vala, src/Views/MediaViewer.vala
Fixed modifier checks not to be affected by NumLock (and other private GDK constants). Fixed MediaViewer and Composer to accept NumPad keys along with alphanumeric block keys.
Fixes #725
=> Fix keyboard shortcuts in editor and media viewer

data/ui/views/sidebar/view.ui
Make Tuba.Widgets.Avatar non-focusable to prevent the child button of accounts selector from being selected during tab-cycling.  It is duplicate to the accounts selector itself.
Closes #729
=> fix: Make Tuba.Widgets.Avatar non-focusable (#729)

src/API/Mention.vala, src/Views/Profile.vala
fix: #731 
Relic of Tootle, it was never converted to use the cacheable internal soup session and never used the token causing GoToSocial to not be able to fetch accounts when mentions got clicked.
=> fix(Mention): use token when opening accounts

src/Application.vala, src/Dialogs/MainWindow.vala, src/Services/Accounts/Mastodon/Account.vala, src/Views/Home.vala, src/Views/Main.vala, src/Views/TabbedBase.vala
fix: #734 
To avoid a breakpoint condition hell, let's just wrap it in another stack.
The problem:
We want the main window to show the main view switcher and switcher bar ONLY in narrow mode (`is-mobile`). To achieve the bottom bar one, is-mobile is bound to its visibility and the main view breakpoint is bound to its reveal property. That way, there are two visibility states. That is not the case for the switcher however, if the switcher is not visible, the headerbar stack cannot set it as the visible child, so both the breakpoint condition and the `is-mobile` one need to be in sync. That led to the previous *very* complicated solution.
This time let's just have 2 visibility states for it, like the switcher bar, using two stacks, one for `is-mobile` and one for the breakpoint.
=> fix(Main): switcher state and breakpoints between is_mobile

src/Widgets/LabelWithWidgets.vala
Previously, the rectangle would go through PANGO_PIXELS to get the new allocation which doesn't match extents_to_pixels' behavior. extents_to_pixels uses PANGO_PIXELS_FLOOR for them. Additionally, extents_to_pixels doesn't seem to pass the rectangle as a reference while also manipulating its width and height which we don't use. So instead use the manipulation we need only
=> fix(LWW): follow extents_to_pixels for allocation

src/Services/Accounts/SecretAccountStore.vala
fix: #701 #114 again 
When searching for secrets (saved accounts) in the keyring, we encountered issues with the keyring not unlocking in some setups. The solution was to retrieve ALL secrets that match the schema and not just Tuba's (#134, #114). However when working on another app that used the same schema as Tuba's I noticed that the two were reading each other's secrets and failing to load them (as expected) so I reverted the change on #701. Now there are two problems, both #114 and the one just described.
It reverts #701 but to prevent the new problem, it checks if the label is "Mastodon Account" (not so reliable) and if `xdg:schema` matches the app id (`dev.geopjr.Tuba`) and skips the secret if it doesn't.
=> fix(SecretAccountStore): workaround DONT_MATCH_NAME

src/Services/Accounts/SecretAccountStore.vala
Enough fighting libsecret. Just do partial content validation until the schema bump.
I added `tuba-id` to the secret as a way to avoid validating the whole object but honestly it should probably be removed. Between the uuid migration and this, a force save might render some secrets unusable (null uuid) and I'm not willing to break the secrets in a patch release
fix: https://github.com/GeopJr/Tuba/pull/742#issuecomment-1886516271
=> fix(SecretAccountStore): rethink validation

src/Services/Helpers/Image.vala
friendica sometimes returns empty strings for images
fix: #745
=> fix(helpers)[image]: do not handle empty urls

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- Fixed DateTime months calculation on dates older than 1 year (#732)
- Fixed MediaViewer not handling numpad keybinds (#726, thanks [at]mgorny)
- Fixed double focus target on sidebar's headerbar account switcher button (#730, thanks [at]mgorny)
- Fixed mentions not opening on GoToSocial (and probably others) due to unauthorized requests to their APIs (#733, thanks [at]daenney)
- Fixed main view being left without a switcher when the initial window size is right at the breakpoint (#735, thanks [at]IBBoard)
- Fixed LabelWithWidgets using a makeshift (and incorrect) `extents_to_pixels` implementation (#720)
- Fixed narrow mode not showing a back button (#718)
- Fixed keyring not being unlocked on some setups due to a libsecret issue and instead manually partially validate secrets (#742, …
```
=> feat: v0.6.2

src/Services/Network/Streams.vala
fix: #750 
Okay so, `NS_ERROR_NET_RESET` errors seem regular on mastosoc
and as expected it doesn't go through the connection error handler so I guess we'll have to do it manually on connection reset by peer. It seems to work!
=> fix(streams): retry on connection reset by peer

src/Dialogs/Composer/Dialog.vala, src/Dialogs/ProfileEdit.vala, src/Views/Sidebar.vala, src/Views/Timeline.vala, src/Widgets/Announcement.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/Status/ActionsRow.vala, src/Widgets/VoteBox.vala
multiple modals on the mainwindow can lock focus. Additionally, set the inform modal's window to the current one on non-mainwindow cases.
fix: #754
=> fix: use toasts when possible to display errors

src/Dialogs/ListEdit.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/Conversations.vala, src/Views/Federated.vala, src/Views/Hashtag.vala, src/Views/Home.vala, src/Views/List.vala, src/Views/Local.vala, src/Views/Notifications.vala, src/Views/Profile.vala
=> fix: /? => ? for query params

src/Views/MediaViewer.vala
Support zooming the Media Viewer via ctrl + mouse wheel scrolling. The controlled needed to be added straight into Gtk.ScrolledWindow, as otherwise it stops working when the media is zoomed in.
Closes #727
=> feat: Support zooming in Media Viewer via ctrl + mouse wheel (#727)

src/Widgets/LabelWithWidgets.vala
fix: #775 #719 
another banger
another banger by gtklabel
<hr />
wrap + ellipsize + lines can sometimes cause the minimum width to be > than the natural one causing the effect found in the linked issues. Setting width-chars to anything but < 1 will skip the measuring :shrug: 
> For ellipsizing labels, if either is specified (and less than the actual text size), it is used as the minimum width, and the actual text size is used as the natural width of the label. For wrapping labels, width-chars is used as the minimum width, if specified, and max-width-chars is used as the natural width. Even if max-width-chars specified, wrapping labels will be rewrapped to use all of the available width.
=> fix(LWW): wrap+ellipsize+lines => min_w > nat_w

data/ui/menus.ui, src/API/Instance.vala, src/Dialogs/Report.vala, src/Dialogs/meson.build, src/Views/Profile.vala, src/Widgets/Status.vala
fix: #786 
TODO:
- ~~Test on every single backend~~
- ~~Add support for reporting profiles on their own~~
[Screencast from 2024-02-19 04-46-17.webm](https://github.com/GeopJr/Tuba/assets/18014039/bc53bf37-8f8f-4b6a-a349-60f01a08f851)
=> feat(dialogs): report

src/Widgets/Status.vala
as always, Vala lambda self ref
Statuses with a kind (like boosted) would stay in memory due to a lambda that would self-ref.
fix: #798 (might not fix everything but at least most of it)
Load -> Load another page -> Refresh
[Screencast from 2024-02-22 11-43-35.webm](https://github.com/GeopJr/Tuba/assets/18014039/103057cb-f48a-472c-84b1-769571192624)
=> fix(Status): memory leak

src/API/Status/PreviewCard.vala, src/Dialogs/MainWindow.vala, src/Views/MediaViewer.vala, src/Widgets/Attachment/Box.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/ProfileCover.vala, src/Widgets/ScaleRevealer.vala
Wow, the media viewer api is getting even more bloated, but hey, at least the pesky carousel animation is gone!
fix: #206 plus Circle review
Okay so:
1. Increased scale revealer animation to 300ms from 200ms. Not really noticeable but having a bit more time is helpful for the fix (else some artifacts are visible for a split second)
2. Removed the position api from the media viewer
3. Added the ability to reveal the media viewer manually - needed to properly do the scale revealer transition from the selected attachment to its image else it will always be from the first one
4. The bug was fixed upstream by scrolling when allocating is done, however due to the scale revealer it doesn't have enough time to, so you see the first image for a split second after the revealer before you see the …
=> fix(MediaViewer): bugs with carousel + multiple items + scalerevealer

src/Utils/Html.vala, src/Widgets/MarkupView.vala
libxml2 started printing errors when provided with empty string, so let's just not handle it when that's the case
=> fix(libxml): ignore empty document

meson.build
During the vapi removal, it wasn't re-implemented, better use an arg instead
=> fix(meson): log domain

src/Application.vala
ngl is becoming the default renderer, and while I wanted Tuba to contribute in testing it, the performance issues are noticeable on less powerful hardware and might be better to wait a bit until everything gets ironed out
Setting `GSK_RENDERER` to `ngl` should work and use the new renderer however.
=> feat: use gl instead of ngl

src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/EditorPage.vala
Same thing as the selectable issue, grabbing focus doesn't work anymore but thankfully, AdwDialog offers a focus-widget prop
fix: #857
=> fix(composer): set the editor as the focused widget

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```md
- Option to darken images on dark mode (#610)
- Notification badges on Account Switcher entries (#767)
- Manpage (#771, thanks [at]danialbehzadi)
- Windows builds (#776)
- More tracking IDs to be stripped (#781, #795, thanks [at]kop316)
- Tracking parameter stripping on paste (#782, thanks [at]kop316)
- 1:1 character counting with Mastodon (including links, graphemes and mentions) (#599, #818)
- Ability to zoom using <kbd>Ctrl</kbd>+ Mouse Wheel on the Media Viewer (#727, thanks [at]mgorny)
- Update the 'verified' icon to one that matches the context better (#740)
- New posts badge on 'Home' (#773)
- Post and User reporting dialog (#787)
- Error toasts when saving attachments (#793)
- Filter handling and editing (#800)
- Unread Announcements banner (#766)
- Hide preview cards from …
```
=> feat: v0.7.0

src/Dialogs/Composer/EditorPage.vala
When the instance doesn't support non-plain-text content type, we never set the default syntax highlighting
to be included in the next patch release
=> fix(composer): default syntax highlighting

src/Dialogs/MainWindow.vala, src/Views/Base.vala, src/Views/ContentBase.vala
fix: #865 
needs memory leak check
a bit weird way to do this but it's the best non-listbox-specific way I could think of
Fixed the focus on media viewer toggling too since it didn't work as expected
=> feat(main_window): keep track of last focused item between navigation changes

src/Views/MediaViewer.vala
fix: #868 ??? (maybe?)
fix: #870 
Noticed a race condition between revealer and todo items. Since we changed the status attachments to reveal the MV at a later point, the MV gets revealed before the items finish resolving.
Instead, make the MV set itself as revealed when the scale transition finishes. At the same time, optimize the todo item resolving by resolving the one to be revealed first and then the rest.
Needs some testing
=> fix(MediaViewer): race condition between reveal and todo

src/Views/MediaViewer.vala
We would only update the reveal widget on swipe prepare, so when moving pages using the buttons and exited the MV, it would exit to another attachment than the current one.
This PR updates it on page change instead. The function is kept as is (carousel position fallback) in case we need to use it in the future.
=> fix(MediaViewer): scale revealer dismiss widget when using the page buttons

src/Widgets/Attachment/Box.vala, src/Widgets/Attachment/Image.vala
on #868 I noticed that audio files do actually have thumbnails sometimes, so let's give their overlay icon the osd style so it doesnt blend in the background. Only when there's a thumbnail.
Oh also memory leak
=> fix(attachments): audio thumbnail icon

build-aux/dev.geopjr.Tuba.Devel.json, data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- Syntax highlighting not working if there are no available content types (#864)
- Keyboard navigation focus not being remembered between NavigationView page changes and MediaViewer reveal toggling (#866)
- Changed brand colors to ones with more contrast (#867, thanks [at]bertob)
- MediaViewer videos playing before being initialized and MediaViewer buttons not being updated to support the video layout due to a race condition (#869)
- MediaViewer scale revealer dismiss widget updating only when gestures are used instead of page changes, causing it to show a different widget when dismissing without using gestures (#872)
- Post audio attachments not having an overlay icon background when there's a thumbnail available (#873)
- It was omitted from the last changelog, but since v0.7.0, Tuba …
```
=> feat: v0.7.1

data/dev.geopjr.Tuba.metainfo.xml.in
It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
=> appdata: `translate=no` properties

data/ui/dialogs/filter_edit.ui, data/ui/dialogs/profile_edit.ui
Marking translatable="yes" or translatable="1" actually achieves the same result, but almost all projects use the first one.
It's good to follow common practices.
=> ui: Fix translatable usage

src/Application.vala
fix: #885 
On 46, GTK defaults to ngl as its renderer. While it's a nice step forward, performance is not on par with gl yet and is very noticeable on Tuba, so we forced `gl` as the default on #847 until everything gets ironed out (gl is being used only if nothing else is set, so you can still override it).
On #885 an issue with fractional scaling and blurriness was raised and after researching on GTK's issue tracker, I discovered that setting `GDK_DEBUG=gl-no-fractional` reproduced the old behavior. This PR sets that if the renderer is gl.
=> fix: fractional scaling blurriness with gl

data/screenshots/screenshot-1.png, src/Dialogs/DevConsole.vala
=> feat(devmode): Flathub screenshot size for banner

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- Better main screenshot for the banner (#887, thanks [at]bertob)
- Marking strings as non-translatable on metainfo (#877, thanks [at]yakushabb)
- Inconsistent 'translatable' values (#884, #889, thanks [at]yakushabb)
- Fractional scaling blurriness due with due to using gl instead of ngl (#886)
**Full Changelog**: https://github.com/GeopJr/Tuba/compare/v0.7.1...v0.7.2
```
This marks the end of the patching period, further commits will be available on 0.8
=> feat: v0.7.2

src/Dialogs/Composer/EditorPage.vala, src/Dialogs/ProfileEdit.vala
fix: #895 
The first commit will fix it but I'm not sure if the second should be merged.
The first issue is that Pixelfed for some reason broke their custom emojis api but also Vala's optional chaining not working as always. So it could be null and still return as truthy.
The second issue, which was just critical logs from json glib but should be taken into account, was that when attempting to get the json root, it could *not* be an object, as many edge cases are valid json but useless to us.
It makes sense to check but is also useless to assume that a server could *not* return an object. Well, if they implement mastoapi that is.
=> fix(composer): pixelfed posting

src/Views/MediaViewer.vala
Regression: #728
fix: #899
Not sure why, but the child's `EventControllerScroll` only handling vertical scrolling blocked the horizontal one from propagating to the parent (Carousel). It makes sense somewhat.
=> fix(MV): horizontal swaping

data/langs/fedi-basic.lang
fix: #898 
Only match them if they start after a non-word or start of content
=> fix(syntax-highlighting): only match whole words

.github/workflows/build.yml, build-aux/dev.geopjr.Tuba.Devel.json, src/Views/MediaViewer.vala
In order to allow pass-through of video content to Wayland compositors, reducing copies on the GPU and thus improving battery life and performance.
This change should generally be safe to do, however given the higher chances of triggering driver bugs good testing is due.
---
An easy way to test this is to look at `intel_gpu_top`/`radeontop`/ similar tools - in many cases this should be able to reduce GPU work considerably, especially for high-res content.
Note that for now it only affect hardware-decoded content - this will hopefully change in the future.
Draft because:
=> feat(MediaViewer): enable GraphicsOffload for videos

data/ui/widgets/status.ui, src/Views/Profile.vala, src/Widgets/Avatar.vala, src/Widgets/ProfileCover.vala, src/Widgets/Status.vala
fix: #495 
fix: #774 
I made sure to make it have as minimal of a resource footprint by enabling it only on posts and making the popovers along with their contents get disposed.
Enabling it on other widgets would be trivial.
=> feat: secondary click popover mini profile

src/API/Akkoma/Translation.vala, src/API/Akkoma/meson.build, src/API/Attachment.vala, src/API/Instance.vala, src/API/InstanceV2.vala, src/API/PollOption.vala, src/API/Status.vala, src/API/Translation.vala, src/API/meson.build, src/Application.vala, src/Services/Accounts/InstanceAccount.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Attachment/Item.vala, src/Widgets/Status.vala, src/Widgets/VoteBox.vala
=> feat: translations

src/API/Status.vala, src/Views/Base.vala, src/Views/ContentBase.vala, src/Views/Lists.vala, src/Views/TabbedBase.vala, src/Views/Timeline.vala
This should fix all the random segfaults
Ref cycles would prevent Views from being destroyed. They would drop from \~60 to \~50 refs. That would also prevent websockets from closing.
Disposing unrefs everything, allowing them to be freed from memory however that had the cost of... losing reference to them and their children sometimes.
After some debugging, I pinned it down to `Gtk.ListBox#bind_model`. We have to clear the binding when it's time to be disposed, but there's no appropriate stage to do that on as dispose or destroy won't ever be called because of it.
Instead, manually remove the binding when it's time to be disposed, by using the same hack as before. The difference now is that we gracefully allow the view and its children to be destroyed, giving also the chance to notice and …
=> feat(Views): stop disposing

src/API/Notification.vala, src/API/Status/PreviewCard.vala, src/Application.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/MainWindow.vala, src/Dialogs/NewAccount.vala, src/Services/Accounts/Mastodon/Account.vala, src/Services/Accounts/SecretAccountStore.vala, src/Utils/Host.vala, src/Utils/Tracking.vala, src/Views/MediaViewer.vala, src/Views/Profile.vala, src/Views/Thread.vala, src/Widgets/Attachment/Item.vala, src/Widgets/BookWyrmPage.vala, src/Widgets/PreviewCard.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala
- Tuba will now open web+ap urls in-app (e.g. `web+ap://faraway.town/@GeopJr` will open my profile in-app instead of going through the process of asking your OS to open the default app for `web+ap` uris)
- Hashtag url resolving is now a lot more strict and valid (by using GLib.Uri)
- Host.open_uri was split into another method for opening GLib.Uris instead of strings
- Link resolving was optimized thanks to the above to use only one GLib.Uri instance instead of creating multiple for every single thing (checking the uri scheme to see if it's web+ap, tracking parameter splitting etc...)
- Fixed a critical in Utils/Tracking when attempting to iterate null query parameters
- Should_resolve conditions were optimized and became stricter
=> feat(RichLabel): cleanup

data/ui/dialogs/compose.ui, data/ui/dialogs/new_account.ui, data/ui/dialogs/profile_edit.ui, data/ui/views/base.ui, data/ui/views/media_viewer.ui, data/ui/views/sidebar/view.ui, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/MainWindow.vala, src/Dialogs/Report.vala, src/Views/Profile.vala, src/Widgets/Attachment/Item.vala
=> fix: make all headerbar centering policies loose

data/style.css, data/ui/dialogs/preferences.ui, data/ui/views/profile_header.ui, data/ui/views/sidebar/account.ui, data/ui/views/sidebar/item.ui, data/ui/widgets/profile.ui, src/API/NotificationFilter.vala, src/API/meson.build, src/Dialogs/Preferences.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/NotificationRequests.vala, src/Views/NotificationRequestsList.vala, src/Views/Notifications.vala, src/Views/meson.build, src/Widgets/NotificationRequest.vala, src/Widgets/Status/FollowRequestRow.vala, src/Widgets/meson.build
Mastodon 4.3 introduced notification requests / junk. Users set a policy for rejecting notifications, like if the actor is a new account or doesn't follow you etc. and when they send you a notification, it ends up in a dedicated space where you can see them, dismiss them or accept them.
This PR adds the whole feature: Dedicated space for them, approving/declining and policy settings
<hr />
This is undocumented so far, but I did write the spec to keep track of it myself, in case any other fellow fedidevs need it:
- `filter_not_following` : `Bool`
Whether you are filtering people you don't follow
- `filter_not_followers` : `Bool`
Whether you are filtering people that do not follow you
- `filter_new_accounts` : `Bool`
Whether you are filtering accounts created the past 30 days
- …
=> feat(Notifications): requests

src/Widgets/Status.vala
Status aria label did not take into account filters. When there's a filter, the 'unfiltered' aria label should absolutely not be available as it will reveal the content.
=> fix(status): filter accessibility

src/Dialogs/Composer/AttachmentsPage.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Composer/Page.vala, src/Dialogs/Composer/PollPage.vala
Ages ago, we had to dispose the composer due to an undefined/unfixable memory leak. Some experience on fixing leaks later, we now now that it's lambdas and bind_models. For bind_models, I used the same workaround as timelines - removing all items when its time to clean them aka when the window closes. For lambdas, the typical moving them into their own methods. This time however, using bind_property without lambdas would also leak, so they became notifications.
On #805, tuba would segfault due to libspelling. That was because the user would close the composer while libspelling was finishing a task, and since closing required disposing, the composer page would get disposing along with libspelling before it was done and result into a segfault.
fix: #805
=> feat(Composer): goodbye dispose

data/style.css, data/ui/widgets/preview_card.ui, src/Widgets/PreviewCard.vala, src/Widgets/Status.vala
After the discussion on https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2109127, I believe the vertical layout is more desirable nowadays. Not only does it match the other platforms but also websites usually have large and wide preview images.
Link with image
Link without image
Without an image seems a bit wasteful, we could make it use the horizontal layout then or remove the image part completely.
Additionally, I noticed that mastodon-web doesn't show preview cards if there are attachments which seems logical, so I made Tuba do it too.
We could also increase the description to 2+ lines since we now have the height freedom to do so
cc: @bertob
=> feat(PreviewCard): redesign

data/ui/widgets/preview_card.ui, src/Widgets/PreviewCard.vala
fix: #986
Pango lines miscalculation? setting wrap to true seems to fix it
=> fix(preview_card): pango lines + ellipsize overflow

data/style.css, src/Widgets/ProfileCover.vala
on odd amount of fileds, the last item would get a border right. That's was so it wouldn't look like it was expanded on the last row. When there's only a single item however, it should look like expanded
#983
=> fix(profile-cover): remove single field border hack

src/Application.vala, src/Widgets/Account.vala, src/Widgets/ProfileCover.vala, src/Widgets/RelationshipButton.vala
fix: #937
The idea is that when the non-mini profile cover invalidates a relationship, the account widget relationship button will update with the new relationship through a global signal from app
=> feat(Widgets.Account): reactive relationships

src/Dialogs/Composer/Completion/CompletionProvider.vala, src/Dialogs/Composer/Completion/EmojiProvider.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala
I hate hate hate hate this
So it now *attempts* to capture the whole word, from start to end.
Is it efficient? NO
Is it reliable? MAYBE
Is it the best we've got? YES
fix: #779
fix: #920
=> fix(CompletionProvider): word capturing

src/Services/Helpers/Image.vala, src/Widgets/Emoji.vala
Suggested by Fabian on matrix, instead of going through libsoup's cache process, let's look it up ourselves.
Why? Because libsoup does complex cache checking that also needs to be decoded:
- Libsoup will respect etag, max cache and other headers
- Whether it hits cache or not, it still needs to go through all the process of getting decoded, orientation fixed etc
Compared to just, checking if the file exists already and loading it.
Libsoup's cache **is important**, especially on profile avatars and API responses. It's not that much on emojis and in situations where it has to load thousands at the same time (CEP), this seems faster
Quirk: libsoup maps images to cache entries using g_str_hash based on the url
=> feat(emoji): libsoup cache lookup

src/Views/MediaViewer.vala
fix: #1006 
When offload is enabled, media_stream might be null by the time `done` is called. Technically, that shouldn't be the case. `done` is called *after* the video finishes downloads and gets set.
Either way, now if `media_stream` is null, it will listen to its notify signal, and if it becomes non-null it will proceed with the `done` process.
Now there's the following criticals:
```
(dev.geopjr.Tuba:179669): GStreamer-Player-CRITICAL **: 00:09:55.248: gst_player_set_mute: assertion 'GST_IS_PLAYER (self)' failed
(dev.geopjr.Tuba:179669): GStreamer-Player-CRITICAL **: 00:09:55.248: gst_player_set_volume: assertion 'GST_IS_PLAYER (self)' failed
(dev.geopjr.Tuba:179669): GStreamer-Player-CRITICAL **: 00:09:55.248: gst_player_set_mute: assertion 'GST_IS_PLAYER (self)' failed …
```
=> fix(mv): video offload crash

meson.build, src/Views/MediaViewer.vala
fix: #1006 
Follow up to the last fix. The issue has to do with the stack. For now let's just avoid using it and straight up show the video without the spinner.
Also locked graphics offload behind gtk 4.14
=> fix(mv): graphics offload crash with stack

src/Views/Timeline.vala
Reported on matrix.
Due to race conditions or websocket reconnections or weird server behavior, a websocket might send a post multiple times or the post might already be there. To work around that, let's just check the first page and remove any posts that share the id of the new post.
=> fix(Timeline): duplicate posts due to race condition

src/Views/TabbedBase.vala, src/Views/Timeline.vala
on_content_changed runs when the content has changed. While it does run when the model's items change, it would also run at the end of requesting a page.
From what I can remember that was so we dealt with empty timelines, aka, when the request ends successfully but the model wasn't changed as there are no items in the timeline.
on_content_changed main use, while virtual, is to change the base status: are there any items? show the timeline, are there no items? show the empty state, is there an error? show the error view. So if it was ran multiple times it wouldnt have any noticeable effect.
But, at some point in 0.7, I added mass relationship requests. Instead of requesting every single account's relationship status, we can now do many at once, thus avoiding spamming the instance. This is …
=> fix(Timeline): double content changed calls

data/ui/dialogs/advanced_search.ui
no need to regen potfile as it was already marked in a different instance
=> fix(advanced-search): mark title as translatable

src/Services/Accounts/InstanceAccount.vala
fix: https://github.com/GeopJr/Tuba/pull/995#issuecomment-2175857425 (partially)
The issues with counting still apply:
> Agreed, though I don't think I can completely get rid of it. The way marking notifications as read works, is by setting a 'marker' to the last read notification. So, while I can avoid increasing the count when Tuba received a filtered notification type, it won't be able to do it if the marker increased while offline. E.g. You make a post and close Tuba. All notification have been read. While offline, you get 10 favourites. When you re-open Tuba the marker will be less than the last notification id, so now there are 10 unread notifications you can't see because they are filtered...
But now, if Tuba, while running, receives an excluded notification, it won't increase the …
=> feat(InstanceAccount): do not increase the notification counter on excluded types

src/Views/Notifications.vala
Prior to this we only updated the exclusion filters on construct. However when the account changed, it wouldnt update them. It does now.
=> fix(Notifications): update exclusion filters when the account changes

data/style.css, data/ui/dialogs/advanced_search.ui, src/Views/Search.vala
Icons look better but are inaccessible, this PR turns the entry icons (like the clear entry and the advanced filters one) into buttons. One tricky part was that styling wise, buttons have min w/h and paddings.
=> fix(Search): accessibility by turning the icons into buttons

src/Services/Accounts/InstanceAccount.vala, src/Services/Settings.vala
We need each instance account to use its own settings for notification filtering. Not very happy with this but I don't think there's a better way.
=> fix(instanceaccount): use self's settings

src/Views/MediaViewer.vala
=> fix(MV): is-ready never being called for images on 4.14

src/Views/MediaViewer.vala
Managed to reproduce the pinch to zoom issue somewhat reliably, I think adding the pinch controller directly to the carousel is probably the best solution.
=> fix(mv): gestures not working always

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
```
- gsettings options to disable graphics offload in runtime, in case it crashes (#1028)
- Media Viewer gestures requiring an extra click sometimes to work (#1030)
- Media Viewer images not being marked as loaded (#1026)
**Full Changelog**: https://github.com/GeopJr/Tuba/compare/v0.8.0...v0.8.1
```
=> feat: v0.8.1

src/Utils/Blurhash.vala
when running the test suite with ubsan (-Db_sanitize=undefined):  
```
10/10 Blurhash                        FAIL            0.10s   killed by signal 6 SIGABRT
>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=35 /home/demon/src/Tuba/out/tests/Blurhash
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
TAP version 13
1..4
stderr:
/home/demon/src/Tuba/src/Utils/Blurhash.vala:48:16: runtime …
```
=> fix(Blurhash): fix signed int multiplication overflow

data/style.css, src/Widgets/Avatar.vala
=> fix(Avatar): drop the popover's padding (#1042)

src/Widgets/Avatar.vala
On #1043 I made a commit on top of the PR to avoid an extra call to add a class. However that ended up replacing the other classes the popover had.
In their infinite knowledge and UX expertise, GitHub decided that comments on reviews can end up as 'Pending' requiring submission. They appear to the author but nobody else :upside_down_face: I ended up merging my changes without ever seeing the additional comments made in that PR.
=> fix(mini-profile): do not replace style classes

data/style.css, src/Widgets/Background.vala
On #1043 I noticed that the focus ring style broke. The background has a border radius on large but doesn't on all other sizes. The focus ring should reflect that.
=> fix(profile-cover): background focus ring

data/dev.geopjr.Tuba.gschema.xml
fix: #1025 #1048
Graphics offload is awesome but the random segfaults under *some* hardware are just so out of my control that I'd rather disable it for now.
Initially, the issue was the loading stack, but even after removing that, it still crashes on other people's hardware (it fixed it for me).
It's just not worth it. I can't even create a reproducer easily.
=> fix(mv): set use-graphics-offload to false

src/Services/Network/Streamable.vala
fix: #1056 
Why were they getting url decoded to begin with?
=> fix(streams): do not url deocde payloads

data/style.css, src/API/Attachment.vala, src/Dialogs/Admin/Report.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/Composer/Completion/EmojiProvider.vala, src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/ProfileEdit.vala, src/Services/Helpers/Image.vala, src/Views/MediaViewer.vala, src/Widgets/Account.vala, src/Widgets/Announcement.vala, src/Widgets/Attachment/Image.vala, src/Widgets/Avatar.vala, src/Widgets/BookWyrmPage.vala, src/Widgets/Emoji.vala, src/Widgets/PreviewCard.vala, src/Widgets/ProfileCover.vala
fix: #1034
- Blurs and grayscales media in reports, reveals them on hover
- Letterboxes media despite app settings (admins need to be able to see the whole image)
- Does not remove the spoiler, but instead shows it revealed
- Does not cache media
=> feat(admin-dashboard): protect admins from illegal media

src/Dialogs/MainWindow.vala, src/Views/Base.vala
~~Turns out that checking if last_widget (weak ref) is null is not enough, we actually have to check if it's also a widget.~~
Turns out that using weak ref at all is segfaulty :shrug: let's just use a normal ref and hope for no memory leaks (couldn't find any in my testing, we do try to clear the ref as often as possible (after the focus has been used, when the model gets cleared))
On my side, that resulted in a CRITICAL, but it turns out it can segfault too
fix: #1059 
<sub>When I'm in a 'why is this happening' competition and my opponent is vala</sub>
=> fix(MainWindow): check if last_widget is a GtkWidget before using

meson.build, src/Views/MediaViewer.vala
Per #1064, graphics offload crashes were fixed upstream and will be available on 4.16. This PR adds a meson check for 4.16 which sets GO to enabled and removes all the hacks we made to fix it on 4.14.
Eventually, when 4.16 releases, anything <4.16 will have GO disabled and use-graphics-offload will be removed.
=> feat(mv): enable graphics offload on 4.16

src/Dialogs/Composer/EditorPage.vala
Just stumbled upon the tracking param stripper in action – thanks for having that! – and noticed that my translation of the string was wrong as I had translated "Stripped" as an adjective rather than as a verb. This PR adds a comment clarifying what to do for translators.
=> fix(translation): Add context to tracking param string 

src/Views/MediaViewer.vala
Some fixes mainly related to handling multiple GIFV in a single post. More info in individual commits descriptions.
---
Ideally, Tuba could be more efficient by creating a single video instance, putting multiple GIFV in Clapper [Queue](https://rafostar.github.io/clapper/doc/clapper/class.Queue.html) and just switching between them (maybe even with overlaid pre-made [NextItemButton](https://rafostar.github.io/clapper/doc/clapper-gtk/class.NextItemButton.html) / [PreviousItemButton](https://rafostar.github.io/clapper/doc/clapper-gtk/class.PreviousItemButton.html)) instead of creating multiple video instances and switching widgets. Unfortunately, this would be probably too much/hard to implement while retaining support for GtkVideo which is the default backend within a single source code …
=> fix(mv): clapper: GIFV handling fixes

build-aux/dev.geopjr.Tuba.Clapper.json, build-aux/dev.geopjr.Tuba.Devel.json
CI has been failing due to libspelling's build config not being able to find gtk, let's see if 0.3.0 fixes it else we will lock to the previous one
edit:
I really need to start reading the changelogs (but to my defense, I didn't expect libspelling to see that big of an update!)
> Currently, libspelling relies on GTK main until 4.15.5 is released
so do keep this in mind if you are a distributor.
=> fix(flatpak): lock libspelling to 0.2.1

data/ui/dialogs/advanced_search.ui
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2192252
=> fix(advanced-search): focus ring on checkboxes not being centered

src/Widgets/Attachment/Item.vala
For some reason, the scrolledwindow having a margin top makes the undershoot appear with a padding
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2202009
=> fix(alt-text-dialog): flat style margin top

src/Views/MediaViewer.vala
Only show the per-item spinner after 1s has passed of not being loaded, to avoid it being shown very briefly
The implementation follows the dynamic sidebar one, where instead of trying to tame the race condition, it uses a second guard. In this case, the spinner will only be added after 1s if the item is not done loading, however the code can still change its spinning status regardless.
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2202009
=> feat(MediaViewer): only add spinner after 1s

src/Dialogs/MainWindow.vala
Can't remember if there was a reason we popped everything instead of replacing. The current popped signal handler is only used for widget focus wizardy, maybe we should just call on_popped in go_back_to_start?
This removes the back animation
https://gitlab.gnome.org/Teams/Circle/-/issues/193#note_2202009
=> feat(MainWindow): replace navigation stack when going back to start

src/API/Account.vala, src/API/SearchResult.vala, src/API/Status.vala, src/API/meson.build, src/Views/Search.vala, src/Widgets/Account.vala, src/Widgets/MarkupView.vala, src/Widgets/Status.vala
Let's make search query keywords bold!
But it's not ready:
the above problem is that we need to re-calculate the indexes based on the new text, `this is a test and another test` => `this is a <b>test</b> and another test` at this point the length of the string has changed, and we need to get the next `test`'s index from the new string
Problem being, this can be quite time consuming, might be better to just use regex instead.
Also from the first screenshot we can see that join**mastodon** is marked. 'mastodon' is inside a string and while it showed up, it probably only did because of the account name and not the link. We should probably only take into account words that start with the keyword
`mastodonCats` :heavy_check_mark: 
`meowMastodon` :x:
and lastly, words that are <= 3 characters …
=> feat(search): bold matches

src/Application.vala
This is needed for X11 window managers.
=> feat: set icon for the window

.github/workflows/msys2.yml, Makefile, data/gresource.xml, data/style.css, data/ui/widgets/audiocontrols.ui, meson.build, src/API/Status/PreviewCard.vala, src/Application.vala, src/Dialogs/MainWindow.vala, src/Utils/Blurhash.vala, src/Views/MediaViewer.vala, src/Widgets/Attachment/Box.vala, src/Widgets/AudioPlayer/Controls.vala, src/Widgets/AudioPlayer/Player.vala, src/Widgets/AudioPlayer/Stream.vala, src/Widgets/AudioPlayer/Visualizer.vala, src/Widgets/AudioPlayer/meson.build, src/Widgets/Avatar.vala, src/Widgets/Status.vala, src/Widgets/meson.build
I learnt more about gstreamer than I thought I would going into this...
Okay so, audio visualizer. Originally used cairo but converted it to snapshots because getting paintables into an imagesurface is more complicated than expected
If there's a thumbnail, it uses it + its blurhash to get the average color and themes the visualizer accordingly. If the color is too dark, it lightens it up.
https://github.com/user-attachments/assets/da4d77c8-96ce-4923-a5f6-490f5846a340
If there's no thumbnail, it will attempt to use the author's avi. I decided to go with accent color for the visualizer. With adw 1.6 we can get the custom ones too.
https://github.com/user-attachments/assets/5415a5ab-9d5c-4bc9-9aa9-b794a2d5b980
TODO:
=> feat(mv): audio visualizer

src/Dialogs/Composer/AttachmentsPageAttachment.vala
- fpd leaks due to the bindings, let's remove them on unmap
- both utilitydialogs would stay in memory to be reused, let's clear them as soon as possible instead and re-create them if needed
- fpd's bidirectional binding would overwrite the initial value, let's setup the bindings first and then update the initial values
- focus picker osd button should only be visible if there's a thumbnail
=> fix(apa): paper cuts

src/API/Relationship.vala, src/Application.vala, src/Dialogs/Composer/Dialog.vala, src/Dialogs/Preferences.vala, src/Dialogs/Report.vala, src/Services/Accounts/SecretAccountStore.vala, src/Views/Lists.vala, src/Views/Profile.vala, src/Views/Sidebar.vala, src/Widgets/Status.vala, src/Widgets/Status/ActionsRow.vala
This required some internal API changes:
- Question API gained a `child` field for setting its extra-child
- Relationship modify API now accepts arrays of param-value items instead of a single param and a single value
=> feat: mute expiration and notifications policy

data/style.css, data/ui/widgets/preview_card.ui, src/API/Status/PreviewCard.vala, src/Widgets/PreviewCard.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala
Don't really like it as it required making the previewcard a box but, :shrug: 
Button opens the profile, if more authors are listed, it shows them in a popover, if there's no url it's just a label
=> feat(PreviewCard): verified authors

data/gresource.xml, data/ui/widgets/preview_card.ui, data/ui/widgets/preview_card_explore.ui, data/ui/widgets/preview_card_internal.ui, src/API/Instance.vala, src/API/InstanceV2.vala, src/API/Status/PreviewCard.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/ContentBase.vala, src/Views/Link.vala, src/Views/meson.build, src/Widgets/PreviewCard.vala, src/Widgets/PreviewCardExplore.vala, src/Widgets/PreviewCardInternal.vala, src/Widgets/meson.build
The upcoming mastodon versions adds link timelines. That required quite a bit of refactoring as we now need a nested button to access them.
So preview cards were split to preview card (status sub-widget), preview card internal and preview card explore.
TODO: figure out when link timelines are available. To that I think the new api_versions of instance v2 could be helpful.
=> feat(explore): link timelines

src/Widgets/AudioPlayer/Player.vala
Couldn't reproduce reliably so this is guesswork, but sometimes audio would still play even though the player was destroyed for a few seconds. I suspect that this is because the stream gets destroyed after the player.
=> fix(visualizer): stream not getting destroyed in time

src/Application.vala
aka revert: #1093 
it was meant as a temp cleaning solution for people who used tuba's early versions
=> feat: remove old cache cleaner

src/Widgets/AudioPlayer/Stream.vala
When pausing, sometimes the position would move to the next step, let's not update the position when paused.
=> fix(visualizer): position getting updated on pause

src/Widgets/AudioPlayer/Stream.vala
The visualizer felt a bit laggy, I increased the freq to 50000000 and bumped smoothing to 0.2
=> feat(visualizer): increase levels update freq

src/Widgets/ScaleRevealer.vala
fix: #1122 ?
Previously the transition would crossfade between the source widget (attachment) and the target one (mediaviewer) relatively to the transition progress. That creates a seamless transition between them. However as shown on #1122, it also creates an unintended effect around the middle point.
For context, the media viewer's black background's opacity is also relative to the animation.
This PR changes it so as long as the animation progress is over 20%, it won't crossfade. This still looks a bit off, maybe just to me because I've seen it in slow mode.
Another idea would be to make the media viewer's background's opacity get darker sooner so the distorted snapshot of the attachment is not that visible?
whichever the path forward might be, this PR can be optimized further so it's a …
=> feat(ScaleRevealer): finish crossfade early

data/style.css, data/ui/widgets/status.ui, src/Utils/TagExtractor.vala, src/Utils/meson.build, src/Widgets/HashtagBar.vala, src/Widgets/MarkupView.vala, src/Widgets/Status.vala, src/Widgets/meson.build, tests/TagExtractor.test.vala, tests/meson.build
fix: #880 
I tried out different ways to do this and honestly this is probably the best.
- Extracting while parsing the HTML
The way libxml2 traverses through a doc is unpredictable (aka, when it reaches an anchor, you can't exactly get the content, you have to go through it and usually the `#` character and the hashtag name are in different elements). That makes it impossible to detect that an anchor is a hashtag quickly and before parsing and appending it. Same thing for detecting if the last paragraph only has hashtags.
The structure also depends on the backend.
- Extracting them afterwards by parsing the pango markup
While we now have a predictable structure, the same issue as above is still present. It becomes too difficult to reliably detect if the last paragraph is only made of …
=> feat: TagExtractor

src/Application.vala
fix: #197 
When ngl was the default, some users noticed a significant performance regression. So we set the default to be GL (while respecting `GSK_RENDERER`).
On 47, Vulkan became the default renderer and the performance should be much better than ngl.
Both ngl and Vulkan fix many artifacts (like curcular avatars becoming square while scrolling sometimes) and the #197 issue from what I gathered.
=> feat: do not force GL by default

src/Dialogs/Composer/Completion/HandleProvider.vala, src/Dialogs/Composer/Completion/HashtagProvider.vala
fix: #1167
During #1003 (iirc), we improved capturing, which started including the prefix in the captured word. That makes the search apis search for `@[username]`, `#[hashtag]`. While Mastodon seems to be okay with it, other backends might not normalize it (like removing the prefix if it doesn't match their internal structures).
This PR removes the prefix in the handle and hashtag providers when searching.
=> fix(CompletionProvider): remove prefix from searching

data/ui/widgets/votebox.ui, src/Widgets/VoteBox.vala
I kinda forgot about this oops
You can now see results without voting + you can refresh them
=> feat(votebox): show results + refresh

data/style.css, data/ui/widgets/announcement.ui, src/API/EmojiReaction.vala, src/API/Instance.vala, src/API/Notification.vala, src/Services/Accounts/InstanceAccount.vala, src/Views/StatusStats.vala, src/Widgets/Announcement.vala, src/Widgets/EmojiReactionAccounts.vala, src/Widgets/Notification.vala, src/Widgets/ReactButton.vala, src/Widgets/Status.vala, src/Widgets/Status/ReactionsRow.vala, src/Widgets/meson.build
fix: #44 
Not that fond of the chooser buttons
TODO:
=> feat(status): reaction posting

src/Widgets/HashtagBar.vala
Suggested on Matrix by Lukasz, if there is only one hidden hashtag, then just show it instead of showing the show-more button (aka if <= MAX + 1)
=> feat(HashtagBar): show all if MAX + 1

data/ui/dialogs/profile_edit.ui, src/Dialogs/ProfileEdit.vala
fix: #1168
According to the log attached on that issue, it has to do with the property binding in the ui file :shrug: 
Unknown why I cannot reproduce it, maybe aarch64 only?
=> fix(ProfileEdit): bind with parent source

src/Widgets/LabelWithWidgets.vala
fix: #914 
TODO: maybe set it to word only when inside markupview?
=> fix(lww): label measuring when pango wrap is word_char

src/Views/ContentBase.vala, src/Views/Home.vala
The problem:
Revealers still capture scroll and click events, even if the child is not visible. This causes the floating button section at the bottom right to be unclickable and unscrollable under some circumstances.
The compose button specifically, has a margin at the bottom and the space is unusuable.
The fix:
Hijacking the reveal-child and child-revealed to change the visibility before/after child-revealed and before/after we are about to reveal-child
=> fix(Home): floating button scroll gesture capture

src/Widgets/LabelWithWidgets.vala
This reverts commit 3b0e1ca7a353ee2ddc98123495933c70475f52a2.
revert: #1172 
as expected, changing wrap to WORD had unfortunate side effects.
=> revert(lww): label measuring when pango wrap is word_char (#1172)

src/Views/TabbedBase.vala
default is hhomogeneous true
tabbed bases have view switchers that can make the width much larger
hhomogeneous makes the stack width as big as the biggest child, even if it's not visible
fix: #1183
=> fix(TabbedBase): headerbar stack width due to homogeneous

data/ui/widgets/votebox.ui, src/Widgets/VoteBox.vala
There's no point in refreshing an expired poll, remove the button if expired.
=> feat(votebox): dont show results button if the poll has expired

src/Widgets/Attachment/Item.vala
GtkLabel keeps causing issues* in the alt text window, lets replace it with a textview instead since it's scrollable
*whole text being selected when presented, #1194 
fix: #1194
=> feat(alt-text-window): label => textview

data/ui/dialogs/preferences.ui
in many non-Latin scripts e.g. Persian, words like `BlurHash` should be transliterated or they can not be read, understood or identified at all.
=> Let BlurHash to be transliterated for non Latin scripts.

src/Views/Profile.vala
The filtergroup does nothing on the followers/following timelines on profiles, it shouldn't be visible there
=> fix(Profile): hide filtergroup when the timeline source is not statuses

src/Application.vala
https://gitlab.gnome.org/GNOME/libspelling/-/issues/20
=> feat: set text domain codeset to utf8

src/API/Relationship.vala, src/Application.vala, src/Views/Home.vala, src/Views/Timeline.vala
I remember Jeff mentioning this at some point, but when you mute/block an account current loaded posts from them are not removed until refreshed. This PR does that, however, I only enabled it for 'Home'. I don't know if they should be removed from convos/notifications and the other timelines are probably not open that long to require listening to this signal.
edit: found it
fix: #233
=> feat: remove accounts that get muted/blocked from home

src/Views/Timeline.vala
cont. #1206 
Actually, boosts should go too, not only authored.
=> feat: remove boosts when blocking/muting/unfollowing

src/Utils/Host.vala
fix: #1210
On #1210, Łukasz reported and debugged an issue with the way we open uris in browser. We've been using `AppInfo.launch_default_for_uri` with `Gtk.UriLauncher` as a fallback. From what I gathered, the former uses dbus (and we didn't use its async variant, so Tuba froze when it failed), while the later the portal. This PR makes it so it only uses `Gtk.UriLauncher`.
=> fix(Host): use UriLauncher by default

data/ui/views/profile_header.ui, src/API/Account.vala, src/Widgets/ProfileCover.vala
This PR adds support for displaying moved accounts:
https://github.com/user-attachments/assets/dc817d6d-ea03-4fb9-aca1-aa52600552d5
=> feat(ProfileCover): moved accounts

src/Application.vala, src/Dialogs/Composer/Dialog.vala, src/Views/DraftStatuses.vala, src/Views/Sidebar.vala, src/Views/meson.build, src/Widgets/ScheduledStatus.vala
After #1209, this was easy to do but keep in mind that this is not *my* implementation but rather my attempt at working together with other clients:
- There's no draft post api, so clients seem to be using scheduled posts, set to very far in the future (3000+ years)
- This is good because the server validates the draft, keep the attachments saved and syncs them between all clients
- But, it also means that the server has your drafts
=> feat: draft posts

src/Dialogs/NewAccount.vala
fix: #1212
The new account dialog (nad), is still not an adw.dialog, because it can be used both as a standalone window (when there's no accounts) or a modal (when adding another account).
This PR makes it so it can be closed with ESC when it's not standalone. Plus sets the extra settings dialog to be able to be closed.
=> feat(NAD): close on ESC when possible

src/Dialogs/Composer/Dialog.vala, src/Views/ScheduledStatuses.vala, src/Widgets/ScheduledStatus.vala
fix: #1214 
As per my comment on that issue, the API does not allow us to directly edit them but hacking around that, we can delete and reschedule them.
It gets a bit messy with schedule timing however. Since the min is 5 mins, we *cannot* edit scheduled posts that are about to be posted, users first need to reschedule them to a future date and the edit button will appear.
It also leaves a period of error: If a post is to be posted in 6 minutes and the user clicks edit, if they spend 6 minutes in the composer, it will be posted. If they spend 2 minutes in the composer, it won't be able to edit it as the new schedule time will only be 4 minutes in the future.
=> feat(ScheduledStatuses): edit

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Widgets/Status.vala
I saw David post about bluesky warning you before copying a the link of a post that wont be visible to everyone, so I thought I could apply it here too.
When attempting to copy a link of a post that's either direct or private, it will show you a dialog. You can either choose to not be reminded again or copy anyway. The dialog lets you know who can see the post (mentioned people, people that follow you, people that follow the author)
=> feat(Status): warn before copying link to a private post

data/ui/dialogs/list_edit.ui, src/Dialogs/ListEdit.vala
prior to this pr, the members page in the listeditor was a 'remove members' group of switchrows where their active state meant 'do not remove' and the inactive 'remove'.
That's confusing. Let's instead rename the group to 'Members' and have the rows have a checkbutton that indicates removal. If checked => remove.
=> feat(Lists): simplify remove design

data/gtk/help-overlay.ui, src/Application.vala, src/Dialogs/MainWindow.vala, src/Views/Base.vala, src/Views/TabbedBase.vala
This reverts commit 7f8c8d333cc96d18024e5b9b1afb5b0c7836e864.
revert: #1251
fix: #1258 
Global action + AdwDialogs = bad. I quickly tried setting it as a view action or a shortcut, same results. No time to debug this rn we are too close to a release
=> revert: "feat: scroll to top on Home (#1251)"

src/Widgets/AudioPlayer/Player.vala, src/Widgets/AudioPlayer/Stream.vala
unmap is not the 'pre-destroy' stage. Instead connect to the destroy signal since the mediaviewer calls it anyway.
Destroy may be called multiple times, so check if the other objects are available.
=> fix(visualizer): dont destroy on unmap

src/Views/MediaViewer.vala
Update the timeout to 3s which is used both by GtkVideo and ClapperGtkVideo.
Note that the later uses 5s for touch by default, but that could be adjusted via `set_fade_delay()`.
This makes the fullscreen button disappear together with other media controls and matches defaults of other players more closely, making the overall experience more consistant.
=> fix(MediaViewer): Make button-hide-timeout match gtk and clapper

src/Views/Search.vala, src/Widgets/MarkupView.vala
Result bolding is cool and all but some posts and queries can be too long and we should probably limit it a bit for the sake of regex and markdown parsing on huge posts and queries
=> feat(Search): limit query bolding to regular sized results

src/Dialogs/AnnualReport.vala
Accidentally left the default as the TRANSPARENT style
(in my defense, the other styles are cuter)
=> fix(FediWrapped): window should be the default

src/Dialogs/Composer/Schedule.vala
1. typo, calendar month never updated
2. DateTime's get_month is 1-12, representing each month, but GtkCalendar's month starts at 0, so we have to normalize it (aka -1)
=> fix(Schedule): month from iso to GtkCalendar

.github/workflows/msys2.yml, Makefile
last one
make windows and make windows_nsis are non-reversible. Once windows_nsis runs, portable has been tampered with and cannot or should not be uploaded
=> fix(ci): split windows builds into portable and nsis

src/API/Notification.vala, src/API/Status/PreviewCard.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/MainWindow.vala, src/Dialogs/NewAccount.vala, src/Services/Accounts/Mastodon/Account.vala, src/Services/Accounts/SecretAccountStore.vala, src/Utils/Host.vala, src/Views/MediaViewer.vala, src/Views/Profile.vala, src/Views/Thread.vala, src/Widgets/Attachment/Item.vala, src/Widgets/BookWyrmPage.vala, src/Widgets/PreviewCard.vala, src/Widgets/PreviewCardExplore.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala
=> feat(host): async only

data/style.css, data/ui/views/base.ui, src/Views/Base.vala, src/Views/TabbedBase.vala
Sergey pointed out some measuring issues with clamp's .small and .large styles. This PR moves our (quite expensive) width based styling to breakpoints.
Works similarly, just the existence of the `.large-view` is equal to `.large`, otherwise `.small`
=> fix(Base): move styles from Clamp classes to Breakpoints

data/ui/widgets/status.ui
These were the remaining places in Tuba where labels were still being measured width-for-height (at least, on my timeline right now), and with these simple changes, we seem to get rid of them too. See the commit message.
There are likely some more small things here and there; for instance I saw a similarly start-aligned wrappable "By %s" button. That should be avoidable using the same valign=center trick.
=> Avoid measuring labels width-for-height

src/Dialogs/Composer/AttachmentsPage.vala
fix: #1311 
As discovered on the linked issue, Pleroma seems to set supported_mime_types to `application/octet-stream` in an attempt to communicate that everything is supported. However on Tuba, we either use whatever the instance returns or use the built-in list (which is from Mastodon).
That means that since Akkoma returns nothing, Tuba internally accepts everything mastodon does. But for Pleroma's case, when the user selects an `image/jpeg` file, Tuba will see that `image/jpeg` is not in the supported mime types the instance returned which is just `application/octet-stream` and tuba rejected it silently.
This PR makes it so if the only supported mime is `application/octet-stream` then it should be ignored and instead use the internal list.
=> fix(AttachmentsPage): handle `application/octet-stream`

data/style.css, data/ui/widgets/status.ui, src/Widgets/Status.vala
fix: #633 
This should improve performance a bit too.
Here's how thread lines *used* to work:
- Tootle
Thread line was a single GtkImage that changed its alignment and margins based on the ROLE (start, middle, end)
- Tuba before this PR
I had experimented with different approaches without completely moving away from Tootle's and ended up with one GtkImage for the line above the avatar and one for below. They changed visibility based on ROLE (start = bottom visible, middle = both visible, end = top visible)
Now there were two GtkImages when it should be none. The pos over Tootle's approach was better alignment and easier to maintain than guessing margins.
- Tuba after this PR
Using snapshoting, it draws a line based on the ROLE and the avatar's position.
It should be faster and have better …
=> feat(Status): move thread lines to snapshoting

.github/workflows/build.yml, build-aux/dev.geopjr.Tuba.Devel.json
aarch64 => use clang
bump action container to 47
i dont think it will fix uploading
=> fix(ci): flatpak

src/Dialogs/Composer/AttachmentsPage.vala, src/Dialogs/Composer/AttachmentsPageAttachment.vala, src/Dialogs/Composer/Dialog.vala, src/Utils/Units.vala
fix: #1327 
I can't believe this is the best way to do this but it seems to be true.
Looks like `g_ascii_formatd` is the only one forcing dots as the decimal separators. `double#to_string` calls that internally but it includes 17 dec places while we only need 2. So we will cast the float to double and then call format on it with a 2 place decimal.
=> fix: float to string being locale dependent

data/style.css, data/ui/widgets/votebox.ui, src/API/Poll.vala, src/Widgets/VoteBox.vala, src/Widgets/VoteRow.vala, src/Widgets/meson.build
fix: #1264
This took way longer than it should have, but I had to replace the action rows with a custom widget as to replace the title label with LWW.
Since I had full control over it, I went ahead and actually designed a useful API for it, so now VoteBox won't destroy all rows and re-build them on updates. Instead it will update the already made rows.
This assumes that no new poll entries can be added or removed during small updates (translations, show results, voting - does not include post editing, those get updated as expected).
But this big refactor might have introduced bugs in terms of voting and updating so any testing would be appreciated :), specifically daily-use testing and not just making test polls since fedizens use polls in many different ways that test polls will never …
=> feat(Widgets): VoteRow

data/dev.geopjr.Tuba.metainfo.xml.in, meson.build
=> chore: bump version

src/Dialogs/Composer/Page.vala, src/Dialogs/MainWindow.vala, src/Dialogs/Preferences.vala, src/Services/Network/Request.vala, src/Views/Admin/Pages/Base.vala, src/Views/Thread.vala, src/Widgets/Account.vala, src/Widgets/MarkupView.vala, src/Widgets/RichLabel.vala
fix: #1347 
Okay this will fix pretty much all segfaults from our side but at the cost of stuff getting memory leaks, so this needs a thorough leak test on all affected objects.
Let's break it down because if I don't log this, I'll repeat it.
Vala's memory management is ref counting. Weak and Unowned are basically the same thing. Tuba uses weak/unowned in a few places where you'd think the objects would always exist regardless so it shouldn't matter and would save us the headache of memory leaking.
Examples include:
- Array of mention objects straight from the parent status to the content's richlabels. As long as the parent status exists, then they should also exist. Apparently not. #1347 
- Account object in avatars. Same as above, the parent status holds a reference to it so it should …
=> fix: get rid of weak / unowned from our side

src/Views/Main.vala, src/Views/TabbedBase.vala
fix: #1351 
One has to ask why `Gtk.Shortcut` and `Gtk.Shortcut.with_arguments` are separate when `Gtk.Shortcut` accepts NamedActions that can have a target :/ spent way too long on this just to notice that `Gtk.Shortcut.with_arguments` exists...
=> feat(TabbedBase): switch page with alt+number

src/Views/Thread.vala
Apparently, `grab_focus` alone won't make the listbox scroll to it if it's done too early. This PR adds a 100ms timeout.
=> fix(Thread): scroll to opened post

data/ui/dialogs/main.ui
On touchscreen devices, it is possible to hide the sidebar when it is not collapsed by using a touchscreen swipe gesture. The sidebar becomes inaccessible as a result. The gestures should only be enabled when the sidebar is collapsed (an overlay), where it is expected to be shown and hidden with the sidebar button.
=> fix(MainWindow): bind sidebar enable-gestures to `collapsed`

data/dev.geopjr.Tuba.gschema.xml, data/ui/dialogs/preferences.ui, data/ui/widgets/status.ui, src/Dialogs/Preferences.vala, src/Services/Settings.vala, src/Widgets/FadeBin.vala, src/Widgets/LabelWithWidgets.vala, src/Widgets/MarkupView.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala, src/Widgets/meson.build
One of these days I'll make libgeopjr or something because it's a shame for all these custom widgets to not be used in other apps.
Anyway, faded view. Not sure if we should go forward with this but it's configurable enough to be able to auto-reveal with a setting or similar.
https://github.com/user-attachments/assets/19a02fde-db3e-40a5-b35c-25d2c8ef8d32
It could also come with a configurable max-height but for now it's a constant.
=> feat(Widgets): FadeBin

src/Widgets/LabelWithWidgets.vala, src/Widgets/MarkupView.vala, src/Widgets/RichLabel.vala
GNOME 48 is out and one of the important fixes on the GTK side are the labels, thanks to Sergey!
This means that we can finally get rid of the LWW hacks.
fix: #756
fix: #67
fix: #914 
fix: #1219 
and probably others
=> feat(lww): remove hacks

src/Dialogs/Composer/EditorPage.vala
This helps e.g. on screen keyboards to figure out if offering word completion is useful.
=> feat(composer): Suggest word completion

src/Dialogs/ProfileEdit.vala
fix: #1368 
Iceshrimp.NET doesn't have a limit yet (2147483647) on profile fields and Tuba's current design tries to create the max amount of fields that a profile can have, causing it to freeze when trying to create that many rows.
This PR makes it so it either creates them all if there are less than 50 available or none if there are more than 50.
This is a temporary solution until I re-do the UX so you can 'add' rows instead.
=> fix(ProfileEdit): limit profile fields

src/Dialogs/ProfileEdit.vala
fix: #1368 
As mentioned there, profile fields are now dynamic, if you can add more, there's a button to do so.
=> feat(ProfileEdit): dynamically add rows

data/meson.build
appstream-glib is under heavy maintenance mode and recommends using appstream instead.
=> Use appstream for appdata validation test

src/Services/Accounts/AccountStore.vala, src/Services/Accounts/SecretAccountStore.vala
When UUIDs in secrets were added (for anonymity reasons), Tuba added some fallbacks to convert old accounts to the new ones. It's been over 1-2 years since, it's safe to say we can remove the fallback. This doesn't affect you unless you are updating from version 0.2 or something.
=> feat(SecretAccountStore): remove UUID fallback

data/ui/views/sidebar/account.ui
fix: #1153 
Not exactly what I was after, but since I can't set the ellipsization position and having 2 max sub lines looks better IMO as it hides less info.
=> feat(SidebarAccountRow): set subtitle lines to 2

src/Services/Accounts/SecretAccountStore.vala
Okay, I'll put my foot down on this one.
To overcome some bugs found in some keyring implementations in some distros with some keyring backends, we would ignore the secret names.
That is really creating issues and is insecure. To put it simply, secrets look something like this data-wise:
```js
{
app: dev.geopjr.Tuba,
label: "Mastodon Account",
attributes: { login: "@GeopJr@tech.lgbt", version: 1 },
secret: { ... }
}
```
To hack around that issue, we would ignore the app name completely and instead match all secrets that have a `version` attribute. That means that if another app had a secret that had a `version` attribute, Tuba would attempt to load it.
This PR stops that behavior which might re-introduce that issue to affected setups.
=> feat(SecretAccountStore): match name

src/API/Status.vala, src/Dialogs/Composer/Dialog.vala, src/Services/Accounts/Mastodon/Account.vala, src/Widgets/Status/ActionsRow.vala
fix: #1390 
Previously, when replying to a post, Tuba would use the same visibility for privacy reasons (if you reply to a followers-only post, your reply will use followers-only (pre-selected) etc).
But that failed to take into account that the user's default posting visibility might be even more private, aka
default user visibility: followers-only
replying-to post visibility: unlisted
pre-selected visibility: unlisted
which is less private than the user's default.
Now each option has a 'privacy rate', 0 to N, 0 being the least private. When it comes to replying, it will compare the two visibilities' privacy rate and the one with the bigger value will be the pre-selected visibility.
=> feat(Composer): use the most private visibility when replying

data/ui/dialogs/main.ui, src/API/Status/PreviewCard.vala, src/Dialogs/MainWindow.vala, src/Views/Browser.vala, src/Views/Profile.vala, src/Widgets/RichLabel.vala, src/Widgets/Status.vala
Not sure if i like this (SSL icon has proper margin since the screenshot)
=> feat(Browser): dialog

src/Dialogs/NewAccount.vala
fix: #1403 
1. Proper URI parsing and manipulation instead of the string manipulations
2. `TUBA_SKIP_STRICT_VALIDATION=1` for skipping the strict validations, specifically `https`, dots in host, port, userinfo
=> feat(NewAccount): proper URI parsing

data/gresource.xml.in, data/meson.build, meson.build
this PR embeds our custom lang specs and styles.
1. it matches upstream's workflow
2. it avoids conflicts
3. it helps package maintainers because they often need to list the usr installed files
=> feat(gresource): embed all lang specs and styles

Makefile, build-aux/dev.geopjr.Tuba.Devel.json, meson.build, meson_options.txt
Use the standard Meson `feature` options to control optional link-time dependencies, as documented in: https://mesonbuild.com/Build-options.html
More specifically, replace the current boolean options that are already present for some of the dependencies with `feature` type options, and add options for the remaining optional dependencies.  These options integrate with `dependency()` calls automatically, making the resulting code simpler and more reliable.  This also makes it possible to disable all the optional dependencies explicitly.
This fixes a bug that Meson would attempt to link to the dependencies (such as `clapper`) even if they were disabled, since disabling the options did not disable the dependency checks, and the dependencies were used in the `final_deps` unconditionally.
I've …
=> feat: use meson features to control optional dependencies

src/Widgets/FadeBin.vala
Something that has been annoying me with FadeBin and in general all these 'fade' views everywhere is that they get applied even if the only thing they are fading is like half a line.
https://github.com/user-attachments/assets/6c29fa25-7f0c-4fd7-8e0a-c258e60aa9a0
To solve that, I'm introducing `MAX_HEIGHT_OVER`, which is `MAX_HEIGHT` + 100. This is the height amount beyond `MAX_HEIGHT` (= 300) that will trigger the fade, aka:
If the height is 350, it won't show the fade, even though it's above MAX_HEIGHT.
If it's 410, it will show the fade and the fade container will be MAX_HEIGHT tall.
This makes sure that expanding a fade bin will actually reveal enough stuff, otherwise it will just not fade it and show it in full.
The above post will now look like this by default because the stuff the …
=> feat(FadeBin): have a minimum beyond the fade min

data/style-hc.css, data/style.css, data/ui/widgets/audiocontrols.ui, src/Widgets/AudioPlayer/Player.vala
\+ feat(Visualizer): clicking video should toggle playing status not reveal state of controls
\+ feat(Clapper): hc border + accented seekbar
=> feat(Visualizer): audio controls match clapper's

src/API/Entity.vala, src/API/Quote.vala, src/API/Status.vala, src/API/meson.build, src/Widgets/Status.vala
\*screams internally\*
Okay so,
akkoma, pleroma and some other software that supported quotes did the very basic thing of extending mastoapi's statuses by adding a `quote` field. That field is of type status aka it's another post.
Now Mastodon is introducing quotes and the approach is different. There's states of the quote, so now the `quote` field is actually not a post but a wrapper around it.
You see where I'm going with this. There's now two different implementations of 'quote' with the same exact key. I'm hacking around this but eventually akko/pleroma will have to catch up.
=> feat(Status): support mastoquotes

data/style.css, src/API/FeaturedTag.vala, src/API/Instance/Mastodon/Configuration/Statuses.vala, src/API/Tag.vala, src/Views/Base.vala, src/Views/Profile.vala, src/Views/Timeline.vala, src/Widgets/ProfileCover.vala
continuation of #1465 
1. `endorsements` is a timeline, so there's no need to do all that breaking
2. it now properly handles source changing
3. it now properly handles filter changing
4. other minor css fixes, empty displaying and base status changing
=> fix(profile): featured streamlining

src/Widgets/FadeBin.vala
FadeBin would measure incorrectly when line height was enabled.
This forces the HORIZONTAL measuring to be for_size -1, no idea if that breaks anything else :shrug:
=> fix(FadeBin): measuring when line height is > 1

src/Widgets/Account.vala, src/Widgets/ProfileCover.vala
When instances have the option to hide your own followers/followings, they set the value to `-1`. We can use to tell the user that the counter is hidden instead of showing -1.
=> feat(Profile): properly hide hidden counters

src/Widgets/FadeBin.vala
fix: #1484 
During the #1426, I made it so it only fades when the height is MAX_HEIGHT + 100, to avoid cases were the height is like MAX_HEIGHT + 1 and the user revealing it ends up only revealing a single pixel of height. Then I made it so the lerp only runs when the sizes are > MAX_HEIGHT + 100 which ended up causing what #1484 tried to fix.
=> fix(FadeBin): lerp on MAX_HEIGHT not OVER

src/Views/Thread.vala
f1x: #1442 
The reason #1442 was possible to happen in the first place was because the root status widget wasn't being destroyed. As always, ref counting bit us, had to make the root_status_widget unowned (let's hope no segfaults will happen).
But this is only 1/3 of #1442
=> fix(Thread): leak with widget

src/Widgets/MarkupView.vala
fix: #1442 
3/3 of #1442 
When making markupview selectable, it only happened in time (loop through children, make them selectable). But if the content gets updated, the new children wouldn't be selectable. It now sets them during append.
=> fix(markupview): set selectable on append

src/Widgets/Status.vala
Status widgets would show a crossfade transition for a few ms when opening a thread that's because the spoiler stack has a transition and it starts on the 'spoiler' child. It now sets the transition to none when changing visible child on bind.
=> feat(status): update spoiler state without transition

src/Widgets/AudioPlayer/Player.vala, src/Widgets/AudioPlayer/Stream.vala, src/Widgets/AudioPlayer/Visualizer.vala
Something that has been bugging me with the visualizer is that the changes are... 'choppy'. To overcome this, I decreased the interval to **50ms**! That was too fast but it *looked* smooth. I now went back to actually do it right.
- Increased to 100ms (which is also the default)
- Linearized all values individually rather than the sum for a more accurate representation
- Started drawing the visualizer using a TimedAnimation with from the previous level to the new value, giving us smooth animations
- Made smoothing 0.4 (doubled), this has a reverse meaning, it made the values less smooth, which is what we wanted since the animation now takes care of the 'big' fluctuations
=> feat(Visualizer): animate changes

src/Views/Drive.vala, src/Views/Profile.vala, src/Views/ScheduledStatuses.vala, src/Views/Thread.vala, src/Views/Timeline.vala
This has also been bugging me for a while.
To have a global way to just refresh, there's a void signal on `app` named `refresh`. Timelines and anything that wants to be refreshed when a user presses ctrl+R or activates the refresh action from the menu, could just connect to it and do their refresh processes then.
But there's a problem with that, let's say you do this:
- Are 'Home'
- Open a Profile
- From there open a hashtag
- Open another profile
Let's count how many timelines are connected to app.refresh: Home, first profile, hashtag timeline, second profile. 4 timelines. Now if you refresh, it will refresh all 4 of them, when it should only refresh the one that's visible.
This PR finally fixes it by checking if the timeline is mapped. So in the above example only the second profile is …
=> feat(timelines): refresh only if mapped

data/ui/widgets/status.ui, src/Widgets/RichLabel.vala, src/Widgets/Status.vala
I've been quite against ellipsizing the name and handle for a long time because... it can lead to impersonators. On the other hand, instances and names are getting longer and longer with many subdomains etc, and on narrow sizes it ends up taking 4-6 lines just to show the handle.
So here's the deal, ellipsize both, handle has a min lines of 2 before ellipsizing.
Case: this is a real instance https://helloeverybodymynameismarkiplierandwelcometofivenightsatfreddys.anindiehorrorgamethatyouguyssuggestedenmasseandisawthatyamimash.playeditandhesaidthatitwasreallyreallygoodsoimveryeagertoseewha.tisupandthatisaterrifyinganimatronicbear.fnaf.stream/
=> feat(status): ellipsize name box

data/ui/dialogs/schedule.ui, src/Dialogs/Composer/Schedule.vala
fix: #1451
A series of unfortunate race conditions led to this.
1. The selected row can be invalid, check
2. That is because `validate` is a callback in builder files and can get called during construction, before the comborow is done. Moved signal bindings to code.
This was only highlighted on Windows, probably due to everything being slower there, but it still applies.
=> fix(schedule): move validation to code from builder callback

data/style.css, data/ui/views/sidebar/account.ui, src/Views/Sidebar.vala
1. Account switcher badges were not in the correct position based on the handle lines, the avatars are now vertically centered so the badges stay in place
2. tab badges were not centered to the background since the font change
3. Account switcher checkmark depended on the selected pseudo but that changed on tab so it now uses a proper class
=> fix: badges position and sizes

src/Dialogs/Composer/Dialog.vala, src/Utils/Locale.vala, src/Views/Search.vala
Also enable ISO-639-3
I won't close #671 yet. It seems that the only way to search both props is to create our own dropdown, but in the meantime this will do.
=> feat: use English locale for expressions on local dropdowns

src/Utils/Exif.vala
we need to unescape the file:// uri before passing to exiv2
=> fix(exif): unescape uri on file://

data/ui/widgets/status.ui
we had an issue with orca getting stuck on the timeline. When it was time to announce a status, it would rapidly use tons of memory until killed. This is now fixed. It was caused by a relation that wasn't valid.
=> fix(status): screen reader getting stuck

data/dev.geopjr.Tuba.gschema.xml, data/dev.geopjr.Tuba.metainfo.xml.in, data/screenshots/screenshot-1.png, data/screenshots/screenshot-2.png, data/screenshots/screenshot-3.png, data/screenshots/screenshot-4.png, data/screenshots/screenshot-5.png, data/screenshots/screenshot-6.png, data/screenshots/screenshot-7.png, data/style.css, meson.build, src/Dialogs/Composer/AttachmentsBin.vala, src/Dialogs/DevConsole.vala, src/Views/Drive.vala, src/Views/Profile.vala
```
- New composer (#623, thanks [at]bertob)
- In-app web browser (#1323)
- Collapse long posts (#1354, thanks [at]bugaevc)
- Grouped notifications (#1193)
- Clapper is now the default video player (#1308)
- Clapper enhancers are now used to play media from third-party services in-app (#1308, thanks [at]Rafostar)
- Desktop notifications will now be withdrawn when viewing the in-app ones (#1322)
- Polls can now display custom emojis (#1342)
- Mastodon quotes support (#1440)
- Iceshrimp Drive (#1408, thanks [at]pancakesmeow)
- Iceshrimp Bubble Timeline (#1482)
- Ability to forward reports to the instances of all involved parties (#1438)
- Tab switching using <kbd>alt</kbd>+<kbd>1/2/3/N</kbd> (#1352)
- Quit App menu entry (#1358)
- Other apps by GeopJr in the about dialog (#1143, thanks …
```
=> feat: 0.10.0

meson.build
Pass both `gexiv2-0.16` and `gexiv2` packages to a single `dependency()` lookup, in order to simplify the logic and fix respecting `gexiv2` option.  This is supported since meson 0.60.0.  The minimum version can be left as `>=0.14`, since `gexiv2-0.16` will always be newer than `>=0.15`.  Thanks to Eli Schwartz for the suggestion.
Fixes #1522
=> fix(meson): fix `gexiv2-0.16` lookup to respect `gexiv2` option

src/Dialogs/Composer/Editor.vala
Hey, I noticed that the `update_spelling_lang ()` method is not found if the `LIBSPELLING` feature is disabled, so compilation without it would fail.
=> fix(build): Tuba doesn't compile without libspelling feature enabled

src/Views/Timeline.vala
Only shows the spinner when y > 15 instead of 0 since they get triggered easily
fix: #1549
=> feat(Timeline): refresh spinner threshold

src/Views/Thread.vala, src/Widgets/Status.vala
root status widget is a weak ref to fix a memory leak. That weak ref can be finalized during the update callback and call its on_edit while its properties have also been finalized. This PR creates an owned reference, updates the widgets and clears it afterwards.
fix: #1544
=> fix(Thread): segfault when destroying weak refs too quick

src/Dialogs/Composer/Editor.vala
Inline status widgets in the composer had a background color that was only somewhat visible in dark mode in the corners. This PR removes the background from the parent listbox.
=> fix(composer): status box background
